// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xebnn_compute.h"

extern XEbnn_compute_Config XEbnn_compute_ConfigTable[];

XEbnn_compute_Config *XEbnn_compute_LookupConfig(u16 DeviceId) {
	XEbnn_compute_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XEBNN_COMPUTE_NUM_INSTANCES; Index++) {
		if (XEbnn_compute_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XEbnn_compute_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XEbnn_compute_Initialize(XEbnn_compute *InstancePtr, u16 DeviceId) {
	XEbnn_compute_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XEbnn_compute_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XEbnn_compute_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

