// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xebnn_compute.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XEbnn_compute_CfgInitialize(XEbnn_compute *InstancePtr, XEbnn_compute_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Inputint_BaseAddress = ConfigPtr->Inputint_BaseAddress;
    InstancePtr->Outputcontrl_BaseAddress = ConfigPtr->Outputcontrl_BaseAddress;
    InstancePtr->Outputint_BaseAddress = ConfigPtr->Outputint_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XEbnn_compute_Start(XEbnn_compute *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEbnn_compute_ReadReg(InstancePtr->Outputcontrl_BaseAddress, XEBNN_COMPUTE_OUTPUTCONTRL_ADDR_AP_CTRL) & 0x80;
    XEbnn_compute_WriteReg(InstancePtr->Outputcontrl_BaseAddress, XEBNN_COMPUTE_OUTPUTCONTRL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XEbnn_compute_IsDone(XEbnn_compute *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEbnn_compute_ReadReg(InstancePtr->Outputcontrl_BaseAddress, XEBNN_COMPUTE_OUTPUTCONTRL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XEbnn_compute_IsIdle(XEbnn_compute *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEbnn_compute_ReadReg(InstancePtr->Outputcontrl_BaseAddress, XEBNN_COMPUTE_OUTPUTCONTRL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XEbnn_compute_IsReady(XEbnn_compute *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEbnn_compute_ReadReg(InstancePtr->Outputcontrl_BaseAddress, XEBNN_COMPUTE_OUTPUTCONTRL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XEbnn_compute_EnableAutoRestart(XEbnn_compute *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEbnn_compute_WriteReg(InstancePtr->Outputcontrl_BaseAddress, XEBNN_COMPUTE_OUTPUTCONTRL_ADDR_AP_CTRL, 0x80);
}

void XEbnn_compute_DisableAutoRestart(XEbnn_compute *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEbnn_compute_WriteReg(InstancePtr->Outputcontrl_BaseAddress, XEBNN_COMPUTE_OUTPUTCONTRL_ADDR_AP_CTRL, 0);
}

u32 XEbnn_compute_Get_input_r_BaseAddress(XEbnn_compute *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Inputint_BaseAddress + XEBNN_COMPUTE_INPUTINT_ADDR_INPUT_R_BASE);
}

u32 XEbnn_compute_Get_input_r_HighAddress(XEbnn_compute *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Inputint_BaseAddress + XEBNN_COMPUTE_INPUTINT_ADDR_INPUT_R_HIGH);
}

u32 XEbnn_compute_Get_input_r_TotalBytes(XEbnn_compute *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XEBNN_COMPUTE_INPUTINT_ADDR_INPUT_R_HIGH - XEBNN_COMPUTE_INPUTINT_ADDR_INPUT_R_BASE + 1);
}

u32 XEbnn_compute_Get_input_r_BitWidth(XEbnn_compute *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEBNN_COMPUTE_INPUTINT_WIDTH_INPUT_R;
}

u32 XEbnn_compute_Get_input_r_Depth(XEbnn_compute *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEBNN_COMPUTE_INPUTINT_DEPTH_INPUT_R;
}

u32 XEbnn_compute_Write_input_r_Words(XEbnn_compute *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XEBNN_COMPUTE_INPUTINT_ADDR_INPUT_R_HIGH - XEBNN_COMPUTE_INPUTINT_ADDR_INPUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Inputint_BaseAddress + XEBNN_COMPUTE_INPUTINT_ADDR_INPUT_R_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XEbnn_compute_Read_input_r_Words(XEbnn_compute *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XEBNN_COMPUTE_INPUTINT_ADDR_INPUT_R_HIGH - XEBNN_COMPUTE_INPUTINT_ADDR_INPUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Inputint_BaseAddress + XEBNN_COMPUTE_INPUTINT_ADDR_INPUT_R_BASE + (offset + i)*4);
    }
    return length;
}

u32 XEbnn_compute_Write_input_r_Bytes(XEbnn_compute *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XEBNN_COMPUTE_INPUTINT_ADDR_INPUT_R_HIGH - XEBNN_COMPUTE_INPUTINT_ADDR_INPUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Inputint_BaseAddress + XEBNN_COMPUTE_INPUTINT_ADDR_INPUT_R_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XEbnn_compute_Read_input_r_Bytes(XEbnn_compute *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XEBNN_COMPUTE_INPUTINT_ADDR_INPUT_R_HIGH - XEBNN_COMPUTE_INPUTINT_ADDR_INPUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Inputint_BaseAddress + XEBNN_COMPUTE_INPUTINT_ADDR_INPUT_R_BASE + offset + i);
    }
    return length;
}

u32 XEbnn_compute_Get_output_r_BaseAddress(XEbnn_compute *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Outputint_BaseAddress + XEBNN_COMPUTE_OUTPUTINT_ADDR_OUTPUT_R_BASE);
}

u32 XEbnn_compute_Get_output_r_HighAddress(XEbnn_compute *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Outputint_BaseAddress + XEBNN_COMPUTE_OUTPUTINT_ADDR_OUTPUT_R_HIGH);
}

u32 XEbnn_compute_Get_output_r_TotalBytes(XEbnn_compute *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XEBNN_COMPUTE_OUTPUTINT_ADDR_OUTPUT_R_HIGH - XEBNN_COMPUTE_OUTPUTINT_ADDR_OUTPUT_R_BASE + 1);
}

u32 XEbnn_compute_Get_output_r_BitWidth(XEbnn_compute *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEBNN_COMPUTE_OUTPUTINT_WIDTH_OUTPUT_R;
}

u32 XEbnn_compute_Get_output_r_Depth(XEbnn_compute *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEBNN_COMPUTE_OUTPUTINT_DEPTH_OUTPUT_R;
}

u32 XEbnn_compute_Write_output_r_Words(XEbnn_compute *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XEBNN_COMPUTE_OUTPUTINT_ADDR_OUTPUT_R_HIGH - XEBNN_COMPUTE_OUTPUTINT_ADDR_OUTPUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Outputint_BaseAddress + XEBNN_COMPUTE_OUTPUTINT_ADDR_OUTPUT_R_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XEbnn_compute_Read_output_r_Words(XEbnn_compute *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XEBNN_COMPUTE_OUTPUTINT_ADDR_OUTPUT_R_HIGH - XEBNN_COMPUTE_OUTPUTINT_ADDR_OUTPUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Outputint_BaseAddress + XEBNN_COMPUTE_OUTPUTINT_ADDR_OUTPUT_R_BASE + (offset + i)*4);
    }
    return length;
}

u32 XEbnn_compute_Write_output_r_Bytes(XEbnn_compute *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XEBNN_COMPUTE_OUTPUTINT_ADDR_OUTPUT_R_HIGH - XEBNN_COMPUTE_OUTPUTINT_ADDR_OUTPUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Outputint_BaseAddress + XEBNN_COMPUTE_OUTPUTINT_ADDR_OUTPUT_R_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XEbnn_compute_Read_output_r_Bytes(XEbnn_compute *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XEBNN_COMPUTE_OUTPUTINT_ADDR_OUTPUT_R_HIGH - XEBNN_COMPUTE_OUTPUTINT_ADDR_OUTPUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Outputint_BaseAddress + XEBNN_COMPUTE_OUTPUTINT_ADDR_OUTPUT_R_BASE + offset + i);
    }
    return length;
}

void XEbnn_compute_InterruptGlobalEnable(XEbnn_compute *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEbnn_compute_WriteReg(InstancePtr->Outputcontrl_BaseAddress, XEBNN_COMPUTE_OUTPUTCONTRL_ADDR_GIE, 1);
}

void XEbnn_compute_InterruptGlobalDisable(XEbnn_compute *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEbnn_compute_WriteReg(InstancePtr->Outputcontrl_BaseAddress, XEBNN_COMPUTE_OUTPUTCONTRL_ADDR_GIE, 0);
}

void XEbnn_compute_InterruptEnable(XEbnn_compute *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XEbnn_compute_ReadReg(InstancePtr->Outputcontrl_BaseAddress, XEBNN_COMPUTE_OUTPUTCONTRL_ADDR_IER);
    XEbnn_compute_WriteReg(InstancePtr->Outputcontrl_BaseAddress, XEBNN_COMPUTE_OUTPUTCONTRL_ADDR_IER, Register | Mask);
}

void XEbnn_compute_InterruptDisable(XEbnn_compute *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XEbnn_compute_ReadReg(InstancePtr->Outputcontrl_BaseAddress, XEBNN_COMPUTE_OUTPUTCONTRL_ADDR_IER);
    XEbnn_compute_WriteReg(InstancePtr->Outputcontrl_BaseAddress, XEBNN_COMPUTE_OUTPUTCONTRL_ADDR_IER, Register & (~Mask));
}

void XEbnn_compute_InterruptClear(XEbnn_compute *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEbnn_compute_WriteReg(InstancePtr->Outputcontrl_BaseAddress, XEBNN_COMPUTE_OUTPUTCONTRL_ADDR_ISR, Mask);
}

u32 XEbnn_compute_InterruptGetEnabled(XEbnn_compute *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEbnn_compute_ReadReg(InstancePtr->Outputcontrl_BaseAddress, XEBNN_COMPUTE_OUTPUTCONTRL_ADDR_IER);
}

u32 XEbnn_compute_InterruptGetStatus(XEbnn_compute *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEbnn_compute_ReadReg(InstancePtr->Outputcontrl_BaseAddress, XEBNN_COMPUTE_OUTPUTCONTRL_ADDR_ISR);
}

