// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __ebnn_compute_l_cojbC_H__
#define __ebnn_compute_l_cojbC_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct ebnn_compute_l_cojbC_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 32;
  static const unsigned AddressRange = 10;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(ebnn_compute_l_cojbC_ram) {
        ram[0] = "0b10111111000011101110010001011011";
        ram[1] = "0b10111110100110110000010001101010";
        ram[2] = "0b10111111000000101011011001010011";
        ram[3] = "0b10111110111100010000110010011001";
        ram[4] = "0b10111110011100110001010110110100";
        ram[5] = "0b10111110101011011101001000001011";
        ram[6] = "0b10111111000000101110010000111011";
        ram[7] = "0b10111110100011010011011100001001";
        ram[8] = "0b10111101111011101010011011011011";
        ram[9] = "0b10111110110100010111111001011111";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(ebnn_compute_l_cojbC) {


static const unsigned DataWidth = 32;
static const unsigned AddressRange = 10;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


ebnn_compute_l_cojbC_ram* meminst;


SC_CTOR(ebnn_compute_l_cojbC) {
meminst = new ebnn_compute_l_cojbC_ram("ebnn_compute_l_cojbC_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~ebnn_compute_l_cojbC() {
    delete meminst;
}


};//endmodule
#endif
