// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __ebnn_compute_l_cohbi_H__
#define __ebnn_compute_l_cohbi_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct ebnn_compute_l_cohbi_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 32;
  static const unsigned AddressRange = 10;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(ebnn_compute_l_cohbi_ram) {
        ram[0] = "0b00111010101010111011011110011001";
        ram[1] = "0b00111010101101110110010101110110";
        ram[2] = "0b00111010111000011101100101111000";
        ram[3] = "0b00111100110001100101001111101101";
        ram[4] = "0b10111011110001011100111100111100";
        ram[5] = "0b00111011010111011000101110001101";
        ram[6] = "0b10111100000110110001000011100011";
        ram[7] = "0b00111011101000100010000111011011";
        ram[8] = "0b10111011000010011101111111000101";
        ram[9] = "0b10111100001110011011011001000010";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(ebnn_compute_l_cohbi) {


static const unsigned DataWidth = 32;
static const unsigned AddressRange = 10;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


ebnn_compute_l_cohbi_ram* meminst;


SC_CTOR(ebnn_compute_l_cohbi) {
meminst = new ebnn_compute_l_cohbi_ram("ebnn_compute_l_cohbi_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~ebnn_compute_l_cohbi() {
    delete meminst;
}


};//endmodule
#endif
