// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __ebnn_compute_l_b_qcK_H__
#define __ebnn_compute_l_b_qcK_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct ebnn_compute_l_b_qcK_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 32;
  static const unsigned AddressRange = 10;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(ebnn_compute_l_b_qcK_ram) {
        ram[0] = "0b01000001101011101110100001100110";
        ram[1] = "0b01000001100010100100000100001111";
        ram[2] = "0b11000001110100011010110011101111";
        ram[3] = "0b11000001011100101111110001111010";
        ram[4] = "0b11000000001001100011111001011111";
        ram[5] = "0b01000001100011110101111111110110";
        ram[6] = "0b01000001000000100011011111111001";
        ram[7] = "0b01000001001001110001100001000110";
        ram[8] = "0b01000001111000010111010000001111";
        ram[9] = "0b01000001110001000011011110111101";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(ebnn_compute_l_b_qcK) {


static const unsigned DataWidth = 32;
static const unsigned AddressRange = 10;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


ebnn_compute_l_b_qcK_ram* meminst;


SC_CTOR(ebnn_compute_l_b_qcK) {
meminst = new ebnn_compute_l_b_qcK_ram("ebnn_compute_l_b_qcK_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~ebnn_compute_l_b_qcK() {
    delete meminst;
}


};//endmodule
#endif
