// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __ebnn_compute_l_b_ocq_H__
#define __ebnn_compute_l_b_ocq_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct ebnn_compute_l_b_ocq_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 32;
  static const unsigned AddressRange = 10;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(ebnn_compute_l_b_ocq_ram) {
        ram[0] = "0b00111111111101001011001010010011";
        ram[1] = "0b00111111111100000000010110010010";
        ram[2] = "0b00111111111010001010111011101011";
        ram[3] = "0b00111111111100100100111110101001";
        ram[4] = "0b00111111111100101110001011010011";
        ram[5] = "0b00111111111010001101010010111011";
        ram[6] = "0b00111111111100101100001010000011";
        ram[7] = "0b00111111111011110111110111010011";
        ram[8] = "0b00111111111010000101010001100000";
        ram[9] = "0b00111111111011000111011111011000";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(ebnn_compute_l_b_ocq) {


static const unsigned DataWidth = 32;
static const unsigned AddressRange = 10;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


ebnn_compute_l_b_ocq_ram* meminst;


SC_CTOR(ebnn_compute_l_b_ocq) {
meminst = new ebnn_compute_l_b_ocq_ram("ebnn_compute_l_b_ocq_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~ebnn_compute_l_b_ocq() {
    delete meminst;
}


};//endmodule
#endif
