// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _ebnn_compute_HH_
#define _ebnn_compute_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "fconv.h"
#include "ebnn_compute_fadddEe.h"
#include "ebnn_compute_fmuleOg.h"
#include "ebnn_compute_fdivfYi.h"
#include "ebnn_compute_sitosc4.h"
#include "ebnn_compute_fcmpg8j.h"
#include "ebnn_compute_temp1.h"
#include "ebnn_compute_l_cohbi.h"
#include "ebnn_compute_l_coibs.h"
#include "ebnn_compute_l_cojbC.h"
#include "ebnn_compute_l_cokbM.h"
#include "ebnn_compute_l_colbW.h"
#include "ebnn_compute_l_b_mb6.h"
#include "ebnn_compute_l_b_ncg.h"
#include "ebnn_compute_l_b_ocq.h"
#include "ebnn_compute_l_b_pcA.h"
#include "ebnn_compute_l_b_qcK.h"
#include "ebnn_compute_l_b_rcU.h"
#include "ebnn_compute_inputINT_s_axi.h"
#include "ebnn_compute_outputCONTRL_s_axi.h"
#include "ebnn_compute_outputINT_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_INPUTINT_ADDR_WIDTH = 17,
         unsigned int C_S_AXI_INPUTINT_DATA_WIDTH = 32,
         unsigned int C_S_AXI_OUTPUTCONTRL_ADDR_WIDTH = 4,
         unsigned int C_S_AXI_OUTPUTCONTRL_DATA_WIDTH = 32,
         unsigned int C_S_AXI_OUTPUTINT_ADDR_WIDTH = 6,
         unsigned int C_S_AXI_OUTPUTINT_DATA_WIDTH = 32>
struct ebnn_compute : public sc_module {
    // Port declarations 54
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > s_axi_inputINT_AWVALID;
    sc_out< sc_logic > s_axi_inputINT_AWREADY;
    sc_in< sc_uint<C_S_AXI_INPUTINT_ADDR_WIDTH> > s_axi_inputINT_AWADDR;
    sc_in< sc_logic > s_axi_inputINT_WVALID;
    sc_out< sc_logic > s_axi_inputINT_WREADY;
    sc_in< sc_uint<C_S_AXI_INPUTINT_DATA_WIDTH> > s_axi_inputINT_WDATA;
    sc_in< sc_uint<C_S_AXI_INPUTINT_DATA_WIDTH/8> > s_axi_inputINT_WSTRB;
    sc_in< sc_logic > s_axi_inputINT_ARVALID;
    sc_out< sc_logic > s_axi_inputINT_ARREADY;
    sc_in< sc_uint<C_S_AXI_INPUTINT_ADDR_WIDTH> > s_axi_inputINT_ARADDR;
    sc_out< sc_logic > s_axi_inputINT_RVALID;
    sc_in< sc_logic > s_axi_inputINT_RREADY;
    sc_out< sc_uint<C_S_AXI_INPUTINT_DATA_WIDTH> > s_axi_inputINT_RDATA;
    sc_out< sc_lv<2> > s_axi_inputINT_RRESP;
    sc_out< sc_logic > s_axi_inputINT_BVALID;
    sc_in< sc_logic > s_axi_inputINT_BREADY;
    sc_out< sc_lv<2> > s_axi_inputINT_BRESP;
    sc_in< sc_logic > s_axi_outputCONTRL_AWVALID;
    sc_out< sc_logic > s_axi_outputCONTRL_AWREADY;
    sc_in< sc_uint<C_S_AXI_OUTPUTCONTRL_ADDR_WIDTH> > s_axi_outputCONTRL_AWADDR;
    sc_in< sc_logic > s_axi_outputCONTRL_WVALID;
    sc_out< sc_logic > s_axi_outputCONTRL_WREADY;
    sc_in< sc_uint<C_S_AXI_OUTPUTCONTRL_DATA_WIDTH> > s_axi_outputCONTRL_WDATA;
    sc_in< sc_uint<C_S_AXI_OUTPUTCONTRL_DATA_WIDTH/8> > s_axi_outputCONTRL_WSTRB;
    sc_in< sc_logic > s_axi_outputCONTRL_ARVALID;
    sc_out< sc_logic > s_axi_outputCONTRL_ARREADY;
    sc_in< sc_uint<C_S_AXI_OUTPUTCONTRL_ADDR_WIDTH> > s_axi_outputCONTRL_ARADDR;
    sc_out< sc_logic > s_axi_outputCONTRL_RVALID;
    sc_in< sc_logic > s_axi_outputCONTRL_RREADY;
    sc_out< sc_uint<C_S_AXI_OUTPUTCONTRL_DATA_WIDTH> > s_axi_outputCONTRL_RDATA;
    sc_out< sc_lv<2> > s_axi_outputCONTRL_RRESP;
    sc_out< sc_logic > s_axi_outputCONTRL_BVALID;
    sc_in< sc_logic > s_axi_outputCONTRL_BREADY;
    sc_out< sc_lv<2> > s_axi_outputCONTRL_BRESP;
    sc_out< sc_logic > interrupt;
    sc_in< sc_logic > s_axi_outputINT_AWVALID;
    sc_out< sc_logic > s_axi_outputINT_AWREADY;
    sc_in< sc_uint<C_S_AXI_OUTPUTINT_ADDR_WIDTH> > s_axi_outputINT_AWADDR;
    sc_in< sc_logic > s_axi_outputINT_WVALID;
    sc_out< sc_logic > s_axi_outputINT_WREADY;
    sc_in< sc_uint<C_S_AXI_OUTPUTINT_DATA_WIDTH> > s_axi_outputINT_WDATA;
    sc_in< sc_uint<C_S_AXI_OUTPUTINT_DATA_WIDTH/8> > s_axi_outputINT_WSTRB;
    sc_in< sc_logic > s_axi_outputINT_ARVALID;
    sc_out< sc_logic > s_axi_outputINT_ARREADY;
    sc_in< sc_uint<C_S_AXI_OUTPUTINT_ADDR_WIDTH> > s_axi_outputINT_ARADDR;
    sc_out< sc_logic > s_axi_outputINT_RVALID;
    sc_in< sc_logic > s_axi_outputINT_RREADY;
    sc_out< sc_uint<C_S_AXI_OUTPUTINT_DATA_WIDTH> > s_axi_outputINT_RDATA;
    sc_out< sc_lv<2> > s_axi_outputINT_RRESP;
    sc_out< sc_logic > s_axi_outputINT_BVALID;
    sc_in< sc_logic > s_axi_outputINT_BREADY;
    sc_out< sc_lv<2> > s_axi_outputINT_BRESP;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<5> > ap_var_for_const1;


    // Module declarations
    ebnn_compute(sc_module_name name);
    SC_HAS_PROCESS(ebnn_compute);

    ~ebnn_compute();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    ebnn_compute_temp1* temp1_U;
    ebnn_compute_l_cohbi* l_conv_pool_bn_bst0_1_U;
    ebnn_compute_l_coibs* l_conv_pool_bn_bst0_4_U;
    ebnn_compute_l_cojbC* l_conv_pool_bn_bst0_3_U;
    ebnn_compute_l_cokbM* l_conv_pool_bn_bst0_5_U;
    ebnn_compute_l_colbW* l_conv_pool_bn_bst0_s_U;
    ebnn_compute_l_b_mb6* l_b_linear_bn_softma_6_U;
    ebnn_compute_l_b_ncg* l_b_linear_bn_softma_1_U;
    ebnn_compute_l_b_ocq* l_b_linear_bn_softma_4_U;
    ebnn_compute_l_b_pcA* l_b_linear_bn_softma_3_U;
    ebnn_compute_l_b_qcK* l_b_linear_bn_softma_5_U;
    ebnn_compute_l_b_rcU* l_b_linear_bn_softma_U;
    ebnn_compute_inputINT_s_axi<C_S_AXI_INPUTINT_ADDR_WIDTH,C_S_AXI_INPUTINT_DATA_WIDTH>* ebnn_compute_inputINT_s_axi_U;
    ebnn_compute_outputCONTRL_s_axi<C_S_AXI_OUTPUTCONTRL_ADDR_WIDTH,C_S_AXI_OUTPUTCONTRL_DATA_WIDTH>* ebnn_compute_outputCONTRL_s_axi_U;
    ebnn_compute_outputINT_s_axi<C_S_AXI_OUTPUTINT_ADDR_WIDTH,C_S_AXI_OUTPUTINT_DATA_WIDTH>* ebnn_compute_outputINT_s_axi_U;
    fconv* grp_fconv_fu_416;
    ebnn_compute_fadddEe<1,5,32,32,32>* ebnn_compute_fadddEe_U26;
    ebnn_compute_fmuleOg<1,4,32,32,32>* ebnn_compute_fmuleOg_U27;
    ebnn_compute_fdivfYi<1,16,32,32,32>* ebnn_compute_fdivfYi_U28;
    ebnn_compute_sitosc4<1,6,32,32>* ebnn_compute_sitosc4_U29;
    ebnn_compute_fcmpg8j<1,1,32,32,1>* ebnn_compute_fcmpg8j_U30;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_lv<51> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_lv<32> > input_r_q0;
    sc_signal< sc_lv<5> > output_r_address0;
    sc_signal< sc_logic > output_r_ce0;
    sc_signal< sc_logic > output_r_we0;
    sc_signal< sc_lv<8> > output_r_d0;
    sc_signal< sc_lv<7> > temp1_address0;
    sc_signal< sc_logic > temp1_ce0;
    sc_signal< sc_logic > temp1_we0;
    sc_signal< sc_lv<8> > temp1_d0;
    sc_signal< sc_lv<8> > temp1_q0;
    sc_signal< sc_lv<4> > l_conv_pool_bn_bst0_1_address0;
    sc_signal< sc_logic > l_conv_pool_bn_bst0_1_ce0;
    sc_signal< sc_lv<32> > l_conv_pool_bn_bst0_1_q0;
    sc_signal< sc_lv<4> > l_conv_pool_bn_bst0_4_address0;
    sc_signal< sc_logic > l_conv_pool_bn_bst0_4_ce0;
    sc_signal< sc_lv<32> > l_conv_pool_bn_bst0_4_q0;
    sc_signal< sc_lv<4> > l_conv_pool_bn_bst0_3_address0;
    sc_signal< sc_logic > l_conv_pool_bn_bst0_3_ce0;
    sc_signal< sc_lv<32> > l_conv_pool_bn_bst0_3_q0;
    sc_signal< sc_lv<4> > l_conv_pool_bn_bst0_5_address0;
    sc_signal< sc_logic > l_conv_pool_bn_bst0_5_ce0;
    sc_signal< sc_lv<32> > l_conv_pool_bn_bst0_5_q0;
    sc_signal< sc_lv<4> > l_conv_pool_bn_bst0_s_address0;
    sc_signal< sc_logic > l_conv_pool_bn_bst0_s_ce0;
    sc_signal< sc_lv<32> > l_conv_pool_bn_bst0_s_q0;
    sc_signal< sc_lv<9> > l_b_linear_bn_softma_6_address0;
    sc_signal< sc_logic > l_b_linear_bn_softma_6_ce0;
    sc_signal< sc_lv<8> > l_b_linear_bn_softma_6_q0;
    sc_signal< sc_lv<4> > l_b_linear_bn_softma_1_address0;
    sc_signal< sc_logic > l_b_linear_bn_softma_1_ce0;
    sc_signal< sc_lv<32> > l_b_linear_bn_softma_1_q0;
    sc_signal< sc_lv<4> > l_b_linear_bn_softma_4_address0;
    sc_signal< sc_logic > l_b_linear_bn_softma_4_ce0;
    sc_signal< sc_lv<32> > l_b_linear_bn_softma_4_q0;
    sc_signal< sc_lv<4> > l_b_linear_bn_softma_3_address0;
    sc_signal< sc_logic > l_b_linear_bn_softma_3_ce0;
    sc_signal< sc_lv<32> > l_b_linear_bn_softma_3_q0;
    sc_signal< sc_lv<4> > l_b_linear_bn_softma_5_address0;
    sc_signal< sc_logic > l_b_linear_bn_softma_5_ce0;
    sc_signal< sc_lv<32> > l_b_linear_bn_softma_5_q0;
    sc_signal< sc_lv<4> > l_b_linear_bn_softma_address0;
    sc_signal< sc_logic > l_b_linear_bn_softma_ce0;
    sc_signal< sc_lv<32> > l_b_linear_bn_softma_q0;
    sc_signal< sc_lv<32> > grp_fu_441_p2;
    sc_signal< sc_lv<32> > reg_461;
    sc_signal< sc_logic > ap_CS_fsm_state19;
    sc_signal< sc_logic > ap_CS_fsm_state24;
    sc_signal< sc_logic > ap_CS_fsm_state49;
    sc_signal< sc_lv<6> > i_fu_474_p2;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<4> > j_2_i_fu_491_p2;
    sc_signal< sc_lv<4> > j_2_i_reg_902;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > exitcond_i_fu_485_p2;
    sc_signal< sc_lv<5> > f_idx_i_fu_506_p3;
    sc_signal< sc_lv<5> > f_idx_i_reg_932;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<32> > l_conv_pool_bn_bst0_8_reg_937;
    sc_signal< sc_lv<32> > l_conv_pool_bn_bst0_10_reg_942;
    sc_signal< sc_lv<32> > l_conv_pool_bn_bst0_12_reg_947;
    sc_signal< sc_lv<32> > l_conv_pool_bn_bst0_14_reg_952;
    sc_signal< sc_lv<32> > l_conv_pool_bn_bst0_16_reg_957;
    sc_signal< sc_lv<9> > tmp_17_i_fu_515_p2;
    sc_signal< sc_lv<9> > tmp_17_i_reg_962;
    sc_signal< sc_lv<9> > next_mul_fu_521_p2;
    sc_signal< sc_lv<9> > next_mul_reg_967;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<32> > max_idx_i_i_cast5_fu_527_p1;
    sc_signal< sc_lv<32> > max_idx_i_i_cast5_reg_972;
    sc_signal< sc_lv<4> > j_i_i_fu_537_p2;
    sc_signal< sc_lv<4> > j_i_i_reg_980;
    sc_signal< sc_lv<6> > i_1_fu_554_p2;
    sc_signal< sc_lv<6> > i_1_reg_988;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<1> > exitcond_fu_548_p2;
    sc_signal< sc_lv<2> > tmp_30_fu_681_p4;
    sc_signal< sc_lv<2> > tmp_30_reg_1008;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<2> > tmp_46_fu_715_p1;
    sc_signal< sc_lv<2> > tmp_46_reg_1013;
    sc_signal< sc_lv<3> > tmp_32_reg_1018;
    sc_signal< sc_lv<10> > res_fu_782_p2;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<64> > tmp_77_i_i_fu_788_p1;
    sc_signal< sc_lv<64> > tmp_77_i_i_reg_1028;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_lv<32> > grp_fu_453_p1;
    sc_signal< sc_lv<32> > res_i_i_reg_1041;
    sc_signal< sc_logic > ap_CS_fsm_state14;
    sc_signal< sc_lv<32> > l_b_linear_bn_softma_9_reg_1046;
    sc_signal< sc_logic > ap_CS_fsm_state18;
    sc_signal< sc_lv<32> > l_b_linear_bn_softma_15_reg_1056;
    sc_signal< sc_logic > ap_CS_fsm_state23;
    sc_signal< sc_lv<32> > l_b_linear_bn_softma_17_reg_1066;
    sc_signal< sc_logic > ap_CS_fsm_state39;
    sc_signal< sc_lv<32> > l_b_linear_bn_softma_11_reg_1081;
    sc_signal< sc_logic > ap_CS_fsm_state40;
    sc_signal< sc_lv<32> > l_b_linear_bn_softma_13_reg_1086;
    sc_signal< sc_lv<32> > grp_fu_449_p2;
    sc_signal< sc_lv<32> > f_assign_6_reg_1091;
    sc_signal< sc_lv<32> > grp_fu_445_p2;
    sc_signal< sc_lv<32> > f_assign_7_reg_1096;
    sc_signal< sc_logic > ap_CS_fsm_state44;
    sc_signal< sc_lv<1> > tmp_25_fu_456_p2;
    sc_signal< sc_lv<1> > tmp_25_reg_1101;
    sc_signal< sc_logic > ap_CS_fsm_state50;
    sc_signal< sc_lv<32> > max_idx_2_i_i_fu_876_p3;
    sc_signal< sc_logic > ap_CS_fsm_state51;
    sc_signal< sc_lv<32> > max_res_1_i_i_fu_883_p3;
    sc_signal< sc_logic > grp_fconv_fu_416_ap_start;
    sc_signal< sc_logic > grp_fconv_fu_416_ap_done;
    sc_signal< sc_logic > grp_fconv_fu_416_ap_idle;
    sc_signal< sc_logic > grp_fconv_fu_416_ap_ready;
    sc_signal< sc_lv<14> > grp_fconv_fu_416_A_address0;
    sc_signal< sc_logic > grp_fconv_fu_416_A_ce0;
    sc_signal< sc_lv<7> > grp_fconv_fu_416_C_address0;
    sc_signal< sc_logic > grp_fconv_fu_416_C_ce0;
    sc_signal< sc_logic > grp_fconv_fu_416_C_we0;
    sc_signal< sc_lv<8> > grp_fconv_fu_416_C_d0;
    sc_signal< sc_lv<6> > i_i_reg_310;
    sc_signal< sc_lv<1> > exitcond1_fu_468_p2;
    sc_signal< sc_lv<4> > j_i_reg_321;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<9> > c_idx_1_i_reg_333;
    sc_signal< sc_lv<4> > max_idx_i_i_reg_345;
    sc_signal< sc_lv<32> > max_idx_1_i_i_reg_357;
    sc_signal< sc_lv<32> > max_res_i_i_reg_369;
    sc_signal< sc_lv<9> > phi_mul_reg_381;
    sc_signal< sc_lv<6> > i_i1_reg_393;
    sc_signal< sc_lv<1> > exitcond_i_i_fu_531_p2;
    sc_signal< sc_lv<10> > res_i_reg_404;
    sc_signal< sc_logic > ap_reg_grp_fconv_fu_416_ap_start;
    sc_signal< sc_lv<64> > tmp_14_i_fu_480_p1;
    sc_signal< sc_lv<64> > tmp_16_i_fu_497_p1;
    sc_signal< sc_lv<64> > tmp_35_i_fu_560_p1;
    sc_signal< sc_lv<64> > sum3_i_cast_fu_575_p1;
    sc_signal< sc_lv<32> > grp_fu_441_p0;
    sc_signal< sc_lv<32> > grp_fu_441_p1;
    sc_signal< sc_logic > ap_CS_fsm_state15;
    sc_signal< sc_logic > ap_CS_fsm_state20;
    sc_signal< sc_logic > ap_CS_fsm_state45;
    sc_signal< sc_logic > ap_CS_fsm_state41;
    sc_signal< sc_logic > ap_CS_fsm_state25;
    sc_signal< sc_lv<32> > grp_fu_453_p0;
    sc_signal< sc_lv<9> > tmp_35_i_cast_fu_565_p1;
    sc_signal< sc_lv<9> > sum3_i_fu_569_p2;
    sc_signal< sc_lv<11> > tmp_38_i_fu_580_p3;
    sc_signal< sc_lv<11> > res_3_fu_588_p2;
    sc_signal< sc_lv<8> > tmp_fu_599_p2;
    sc_signal< sc_lv<8> > v_assign_fu_605_p2;
    sc_signal< sc_lv<1> > tmp_38_fu_611_p3;
    sc_signal< sc_lv<1> > tmp_42_fu_619_p3;
    sc_signal< sc_lv<1> > tmp_44_fu_627_p3;
    sc_signal< sc_lv<1> > tmp_45_fu_635_p3;
    sc_signal< sc_lv<7> > tmp_3_i_i_fu_643_p8;
    sc_signal< sc_lv<8> > tmp_3_i_i_cast_fu_661_p1;
    sc_signal< sc_lv<8> > c_fu_665_p2;
    sc_signal< sc_lv<2> > tmp_29_fu_671_p4;
    sc_signal< sc_lv<6> > tmp_6_i_i_fu_691_p4;
    sc_signal< sc_lv<2> > tmp_31_fu_705_p4;
    sc_signal< sc_lv<6> > tmp_7_i_i_fu_719_p4;
    sc_signal< sc_lv<7> > tmp_6_i_i_cast_fu_701_p1;
    sc_signal< sc_lv<7> > tmp_7_i_i_cast_fu_729_p1;
    sc_signal< sc_lv<7> > c_1_fu_733_p2;
    sc_signal< sc_lv<4> > tmp_27_fu_749_p3;
    sc_signal< sc_lv<4> > tmp_28_fu_756_p3;
    sc_signal< sc_lv<4> > tmp_i_i_cast_fu_769_p1;
    sc_signal< sc_lv<4> > tmp_9_i_i_cast3_fu_763_p2;
    sc_signal< sc_lv<4> > tmp_1_i_i_fu_772_p2;
    sc_signal< sc_lv<10> > tmp_2_i_i_cast_fu_778_p1;
    sc_signal< sc_lv<32> > f_assign_8_to_int_fu_793_p1;
    sc_signal< sc_lv<32> > max_res_i_i_to_int_fu_811_p1;
    sc_signal< sc_lv<8> > tmp_s_fu_797_p4;
    sc_signal< sc_lv<23> > tmp_36_fu_807_p1;
    sc_signal< sc_lv<1> > notrhs_fu_835_p2;
    sc_signal< sc_lv<1> > notlhs_fu_829_p2;
    sc_signal< sc_lv<8> > tmp_21_fu_815_p4;
    sc_signal< sc_lv<23> > tmp_37_fu_825_p1;
    sc_signal< sc_lv<1> > notrhs1_fu_853_p2;
    sc_signal< sc_lv<1> > notlhs1_fu_847_p2;
    sc_signal< sc_lv<1> > tmp_22_fu_841_p2;
    sc_signal< sc_lv<1> > tmp_23_fu_859_p2;
    sc_signal< sc_lv<1> > tmp_24_fu_865_p2;
    sc_signal< sc_lv<1> > tmp_26_fu_871_p2;
    sc_signal< sc_lv<2> > grp_fu_441_opcode;
    sc_signal< sc_lv<51> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<51> ap_ST_fsm_state1;
    static const sc_lv<51> ap_ST_fsm_state2;
    static const sc_lv<51> ap_ST_fsm_state3;
    static const sc_lv<51> ap_ST_fsm_state4;
    static const sc_lv<51> ap_ST_fsm_state5;
    static const sc_lv<51> ap_ST_fsm_state6;
    static const sc_lv<51> ap_ST_fsm_state7;
    static const sc_lv<51> ap_ST_fsm_state8;
    static const sc_lv<51> ap_ST_fsm_state9;
    static const sc_lv<51> ap_ST_fsm_state10;
    static const sc_lv<51> ap_ST_fsm_state11;
    static const sc_lv<51> ap_ST_fsm_state12;
    static const sc_lv<51> ap_ST_fsm_state13;
    static const sc_lv<51> ap_ST_fsm_state14;
    static const sc_lv<51> ap_ST_fsm_state15;
    static const sc_lv<51> ap_ST_fsm_state16;
    static const sc_lv<51> ap_ST_fsm_state17;
    static const sc_lv<51> ap_ST_fsm_state18;
    static const sc_lv<51> ap_ST_fsm_state19;
    static const sc_lv<51> ap_ST_fsm_state20;
    static const sc_lv<51> ap_ST_fsm_state21;
    static const sc_lv<51> ap_ST_fsm_state22;
    static const sc_lv<51> ap_ST_fsm_state23;
    static const sc_lv<51> ap_ST_fsm_state24;
    static const sc_lv<51> ap_ST_fsm_state25;
    static const sc_lv<51> ap_ST_fsm_state26;
    static const sc_lv<51> ap_ST_fsm_state27;
    static const sc_lv<51> ap_ST_fsm_state28;
    static const sc_lv<51> ap_ST_fsm_state29;
    static const sc_lv<51> ap_ST_fsm_state30;
    static const sc_lv<51> ap_ST_fsm_state31;
    static const sc_lv<51> ap_ST_fsm_state32;
    static const sc_lv<51> ap_ST_fsm_state33;
    static const sc_lv<51> ap_ST_fsm_state34;
    static const sc_lv<51> ap_ST_fsm_state35;
    static const sc_lv<51> ap_ST_fsm_state36;
    static const sc_lv<51> ap_ST_fsm_state37;
    static const sc_lv<51> ap_ST_fsm_state38;
    static const sc_lv<51> ap_ST_fsm_state39;
    static const sc_lv<51> ap_ST_fsm_state40;
    static const sc_lv<51> ap_ST_fsm_state41;
    static const sc_lv<51> ap_ST_fsm_state42;
    static const sc_lv<51> ap_ST_fsm_state43;
    static const sc_lv<51> ap_ST_fsm_state44;
    static const sc_lv<51> ap_ST_fsm_state45;
    static const sc_lv<51> ap_ST_fsm_state46;
    static const sc_lv<51> ap_ST_fsm_state47;
    static const sc_lv<51> ap_ST_fsm_state48;
    static const sc_lv<51> ap_ST_fsm_state49;
    static const sc_lv<51> ap_ST_fsm_state50;
    static const sc_lv<51> ap_ST_fsm_state51;
    static const sc_lv<32> ap_const_lv32_0;
    static const int C_S_AXI_DATA_WIDTH;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_30;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<32> ap_const_lv32_26;
    static const sc_lv<32> ap_const_lv32_27;
    static const sc_lv<32> ap_const_lv32_2B;
    static const sc_lv<32> ap_const_lv32_31;
    static const sc_lv<32> ap_const_lv32_32;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<32> ap_const_lv32_FF7FFFFF;
    static const sc_lv<10> ap_const_lv10_0;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<32> ap_const_lv32_2C;
    static const sc_lv<32> ap_const_lv32_28;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<6> ap_const_lv6_2D;
    static const sc_lv<6> ap_const_lv6_1;
    static const sc_lv<4> ap_const_lv4_A;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<9> ap_const_lv9_24;
    static const sc_lv<9> ap_const_lv9_2D;
    static const sc_lv<11> ap_const_lv11_698;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<23> ap_const_lv23_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<5> ap_const_lv5_2;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state14();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state18();
    void thread_ap_CS_fsm_state19();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state20();
    void thread_ap_CS_fsm_state23();
    void thread_ap_CS_fsm_state24();
    void thread_ap_CS_fsm_state25();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state39();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state40();
    void thread_ap_CS_fsm_state41();
    void thread_ap_CS_fsm_state44();
    void thread_ap_CS_fsm_state45();
    void thread_ap_CS_fsm_state49();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state50();
    void thread_ap_CS_fsm_state51();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_c_1_fu_733_p2();
    void thread_c_fu_665_p2();
    void thread_exitcond1_fu_468_p2();
    void thread_exitcond_fu_548_p2();
    void thread_exitcond_i_fu_485_p2();
    void thread_exitcond_i_i_fu_531_p2();
    void thread_f_assign_8_to_int_fu_793_p1();
    void thread_f_idx_i_fu_506_p3();
    void thread_grp_fconv_fu_416_ap_start();
    void thread_grp_fu_441_opcode();
    void thread_grp_fu_441_p0();
    void thread_grp_fu_441_p1();
    void thread_grp_fu_453_p0();
    void thread_i_1_fu_554_p2();
    void thread_i_fu_474_p2();
    void thread_j_2_i_fu_491_p2();
    void thread_j_i_i_fu_537_p2();
    void thread_l_b_linear_bn_softma_1_address0();
    void thread_l_b_linear_bn_softma_1_ce0();
    void thread_l_b_linear_bn_softma_3_address0();
    void thread_l_b_linear_bn_softma_3_ce0();
    void thread_l_b_linear_bn_softma_4_address0();
    void thread_l_b_linear_bn_softma_4_ce0();
    void thread_l_b_linear_bn_softma_5_address0();
    void thread_l_b_linear_bn_softma_5_ce0();
    void thread_l_b_linear_bn_softma_6_address0();
    void thread_l_b_linear_bn_softma_6_ce0();
    void thread_l_b_linear_bn_softma_address0();
    void thread_l_b_linear_bn_softma_ce0();
    void thread_l_conv_pool_bn_bst0_1_address0();
    void thread_l_conv_pool_bn_bst0_1_ce0();
    void thread_l_conv_pool_bn_bst0_3_address0();
    void thread_l_conv_pool_bn_bst0_3_ce0();
    void thread_l_conv_pool_bn_bst0_4_address0();
    void thread_l_conv_pool_bn_bst0_4_ce0();
    void thread_l_conv_pool_bn_bst0_5_address0();
    void thread_l_conv_pool_bn_bst0_5_ce0();
    void thread_l_conv_pool_bn_bst0_s_address0();
    void thread_l_conv_pool_bn_bst0_s_ce0();
    void thread_max_idx_2_i_i_fu_876_p3();
    void thread_max_idx_i_i_cast5_fu_527_p1();
    void thread_max_res_1_i_i_fu_883_p3();
    void thread_max_res_i_i_to_int_fu_811_p1();
    void thread_next_mul_fu_521_p2();
    void thread_notlhs1_fu_847_p2();
    void thread_notlhs_fu_829_p2();
    void thread_notrhs1_fu_853_p2();
    void thread_notrhs_fu_835_p2();
    void thread_output_r_address0();
    void thread_output_r_ce0();
    void thread_output_r_d0();
    void thread_output_r_we0();
    void thread_res_3_fu_588_p2();
    void thread_res_fu_782_p2();
    void thread_sum3_i_cast_fu_575_p1();
    void thread_sum3_i_fu_569_p2();
    void thread_temp1_address0();
    void thread_temp1_ce0();
    void thread_temp1_d0();
    void thread_temp1_we0();
    void thread_tmp_14_i_fu_480_p1();
    void thread_tmp_16_i_fu_497_p1();
    void thread_tmp_17_i_fu_515_p2();
    void thread_tmp_1_i_i_fu_772_p2();
    void thread_tmp_21_fu_815_p4();
    void thread_tmp_22_fu_841_p2();
    void thread_tmp_23_fu_859_p2();
    void thread_tmp_24_fu_865_p2();
    void thread_tmp_26_fu_871_p2();
    void thread_tmp_27_fu_749_p3();
    void thread_tmp_28_fu_756_p3();
    void thread_tmp_29_fu_671_p4();
    void thread_tmp_2_i_i_cast_fu_778_p1();
    void thread_tmp_30_fu_681_p4();
    void thread_tmp_31_fu_705_p4();
    void thread_tmp_35_i_cast_fu_565_p1();
    void thread_tmp_35_i_fu_560_p1();
    void thread_tmp_36_fu_807_p1();
    void thread_tmp_37_fu_825_p1();
    void thread_tmp_38_fu_611_p3();
    void thread_tmp_38_i_fu_580_p3();
    void thread_tmp_3_i_i_cast_fu_661_p1();
    void thread_tmp_3_i_i_fu_643_p8();
    void thread_tmp_42_fu_619_p3();
    void thread_tmp_44_fu_627_p3();
    void thread_tmp_45_fu_635_p3();
    void thread_tmp_46_fu_715_p1();
    void thread_tmp_6_i_i_cast_fu_701_p1();
    void thread_tmp_6_i_i_fu_691_p4();
    void thread_tmp_77_i_i_fu_788_p1();
    void thread_tmp_7_i_i_cast_fu_729_p1();
    void thread_tmp_7_i_i_fu_719_p4();
    void thread_tmp_9_i_i_cast3_fu_763_p2();
    void thread_tmp_fu_599_p2();
    void thread_tmp_i_i_cast_fu_769_p1();
    void thread_tmp_s_fu_797_p4();
    void thread_v_assign_fu_605_p2();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
