// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "fconv.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic fconv::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic fconv::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<44> fconv::ap_ST_fsm_state1 = "1";
const sc_lv<44> fconv::ap_ST_fsm_state2 = "10";
const sc_lv<44> fconv::ap_ST_fsm_state3 = "100";
const sc_lv<44> fconv::ap_ST_fsm_state4 = "1000";
const sc_lv<44> fconv::ap_ST_fsm_state5 = "10000";
const sc_lv<44> fconv::ap_ST_fsm_state6 = "100000";
const sc_lv<44> fconv::ap_ST_fsm_state7 = "1000000";
const sc_lv<44> fconv::ap_ST_fsm_state8 = "10000000";
const sc_lv<44> fconv::ap_ST_fsm_state9 = "100000000";
const sc_lv<44> fconv::ap_ST_fsm_state10 = "1000000000";
const sc_lv<44> fconv::ap_ST_fsm_state11 = "10000000000";
const sc_lv<44> fconv::ap_ST_fsm_state12 = "100000000000";
const sc_lv<44> fconv::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state38 = "10000000000000000000000000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state39 = "100000000000000000000000000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state40 = "1000000000000000000000000000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state41 = "10000000000000000000000000000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state42 = "100000000000000000000000000000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state43 = "1000000000000000000000000000000000000000000";
const sc_lv<44> fconv::ap_ST_fsm_state44 = "10000000000000000000000000000000000000000000";
const sc_lv<32> fconv::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> fconv::ap_const_lv32_B = "1011";
const sc_lv<32> fconv::ap_const_lv32_10 = "10000";
const sc_lv<32> fconv::ap_const_lv32_29 = "101001";
const sc_lv<32> fconv::ap_const_lv32_1 = "1";
const sc_lv<1> fconv::ap_const_lv1_1 = "1";
const sc_lv<32> fconv::ap_const_lv32_2 = "10";
const sc_lv<32> fconv::ap_const_lv32_3 = "11";
const sc_lv<32> fconv::ap_const_lv32_4 = "100";
const sc_lv<1> fconv::ap_const_lv1_0 = "0";
const sc_lv<32> fconv::ap_const_lv32_5 = "101";
const sc_lv<32> fconv::ap_const_lv32_6 = "110";
const sc_lv<32> fconv::ap_const_lv32_20 = "100000";
const sc_lv<32> fconv::ap_const_lv32_24 = "100100";
const sc_lv<32> fconv::ap_const_lv32_2A = "101010";
const sc_lv<4> fconv::ap_const_lv4_0 = "0000";
const sc_lv<32> fconv::ap_const_lv32_2B = "101011";
const sc_lv<32> fconv::ap_const_lv32_FF7FFFFF = "11111111011111111111111111111111";
const sc_lv<32> fconv::ap_const_lv32_7 = "111";
const sc_lv<32> fconv::ap_const_lv32_C = "1100";
const sc_lv<32> fconv::ap_const_lv32_25 = "100101";
const sc_lv<32> fconv::ap_const_lv32_21 = "100001";
const sc_lv<32> fconv::ap_const_lv32_11 = "10001";
const sc_lv<3> fconv::ap_const_lv3_7 = "111";
const sc_lv<8> fconv::ap_const_lv8_1 = "1";
const sc_lv<32> fconv::ap_const_lv32_8 = "1000";
const sc_lv<4> fconv::ap_const_lv4_2 = "10";
const sc_lv<4> fconv::ap_const_lv4_D = "1101";
const sc_lv<4> fconv::ap_const_lv4_3 = "11";
const sc_lv<32> fconv::ap_const_lv32_1F = "11111";
const sc_lv<32> fconv::ap_const_lv32_80000001 = "10000000000000000000000000000001";
const sc_lv<32> fconv::ap_const_lv32_17 = "10111";
const sc_lv<32> fconv::ap_const_lv32_1E = "11110";
const sc_lv<8> fconv::ap_const_lv8_FF = "11111111";
const sc_lv<23> fconv::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<7> fconv::ap_const_lv7_0 = "0000000";
const sc_lv<32> fconv::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<31> fconv::ap_const_lv31_7FFFFFFF = "1111111111111111111111111111111";
const sc_lv<31> fconv::ap_const_lv31_7 = "111";
const sc_lv<2> fconv::ap_const_lv2_0 = "00";
const sc_lv<2> fconv::ap_const_lv2_1 = "1";
const sc_lv<5> fconv::ap_const_lv5_2 = "10";
const sc_lv<5> fconv::ap_const_lv5_3 = "11";
const bool fconv::ap_const_boolean_1 = true;

fconv::fconv(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_fdot_3d_fu_244 = new fdot_3d("grp_fdot_3d_fu_244");
    grp_fdot_3d_fu_244->ap_clk(ap_clk);
    grp_fdot_3d_fu_244->ap_rst(ap_rst);
    grp_fdot_3d_fu_244->ap_start(grp_fdot_3d_fu_244_ap_start);
    grp_fdot_3d_fu_244->ap_done(grp_fdot_3d_fu_244_ap_done);
    grp_fdot_3d_fu_244->ap_idle(grp_fdot_3d_fu_244_ap_idle);
    grp_fdot_3d_fu_244->ap_ready(grp_fdot_3d_fu_244_ap_ready);
    grp_fdot_3d_fu_244->A_address0(grp_fdot_3d_fu_244_A_address0);
    grp_fdot_3d_fu_244->A_ce0(grp_fdot_3d_fu_244_A_ce0);
    grp_fdot_3d_fu_244->A_q0(A_q0);
    grp_fdot_3d_fu_244->B_offset(F_offset);
    grp_fdot_3d_fu_244->x(i_reg_809);
    grp_fdot_3d_fu_244->y(j_reg_818);
    grp_fdot_3d_fu_244->ap_return(grp_fdot_3d_fu_244_ap_return);
    ebnn_compute_fadddEe_U9 = new ebnn_compute_fadddEe<1,5,32,32,32>("ebnn_compute_fadddEe_U9");
    ebnn_compute_fadddEe_U9->clk(ap_clk);
    ebnn_compute_fadddEe_U9->reset(ap_rst);
    ebnn_compute_fadddEe_U9->din0(grp_fu_257_p0);
    ebnn_compute_fadddEe_U9->din1(grp_fu_257_p1);
    ebnn_compute_fadddEe_U9->opcode(grp_fu_257_opcode);
    ebnn_compute_fadddEe_U9->ce(ap_var_for_const0);
    ebnn_compute_fadddEe_U9->dout(grp_fu_257_p2);
    ebnn_compute_fmuleOg_U10 = new ebnn_compute_fmuleOg<1,4,32,32,32>("ebnn_compute_fmuleOg_U10");
    ebnn_compute_fmuleOg_U10->clk(ap_clk);
    ebnn_compute_fmuleOg_U10->reset(ap_rst);
    ebnn_compute_fmuleOg_U10->din0(f_assign_2_reg_853);
    ebnn_compute_fmuleOg_U10->din1(Gamma);
    ebnn_compute_fmuleOg_U10->ce(ap_var_for_const0);
    ebnn_compute_fmuleOg_U10->dout(grp_fu_262_p2);
    ebnn_compute_fdivfYi_U11 = new ebnn_compute_fdivfYi<1,16,32,32,32>("ebnn_compute_fdivfYi_U11");
    ebnn_compute_fdivfYi_U11->clk(ap_clk);
    ebnn_compute_fdivfYi_U11->reset(ap_rst);
    ebnn_compute_fdivfYi_U11->din0(reg_277);
    ebnn_compute_fdivfYi_U11->din1(Std);
    ebnn_compute_fdivfYi_U11->ce(ap_var_for_const0);
    ebnn_compute_fdivfYi_U11->dout(grp_fu_266_p2);
    ebnn_compute_fcmpg8j_U12 = new ebnn_compute_fcmpg8j<1,1,32,32,1>("ebnn_compute_fcmpg8j_U12");
    ebnn_compute_fcmpg8j_U12->din0(grp_fu_270_p0);
    ebnn_compute_fcmpg8j_U12->din1(grp_fu_270_p1);
    ebnn_compute_fcmpg8j_U12->opcode(grp_fu_270_opcode);
    ebnn_compute_fcmpg8j_U12->dout(grp_fu_270_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_A_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_fdot_3d_fu_244_A_address0 );

    SC_METHOD(thread_A_ce0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_fdot_3d_fu_244_A_ce0 );

    SC_METHOD(thread_C_address0);
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( C_addr_reg_868 );
    sensitive << ( ap_CS_fsm_state44 );
    sensitive << ( tmp_1_fu_606_p1 );

    SC_METHOD(thread_C_ce0);
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( ap_CS_fsm_state44 );

    SC_METHOD(thread_C_d0);
    sensitive << ( C_q0 );
    sensitive << ( tmp_8_reg_863 );
    sensitive << ( ap_CS_fsm_state44 );
    sensitive << ( tmp_26_fu_664_p1 );

    SC_METHOD(thread_C_we0);
    sensitive << ( ap_CS_fsm_state44 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state33);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state34);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state37);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state38);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state42);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state43);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state44);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_s_fu_347_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_s_fu_347_p2 );

    SC_METHOD(thread_c_idx_2_fu_645_p2);
    sensitive << ( c_idx_1_fu_100 );
    sensitive << ( tmp_26_cast_fu_641_p1 );

    SC_METHOD(thread_c_idx_cast_fu_318_p1);
    sensitive << ( c_idx_fu_308_p4 );

    SC_METHOD(thread_c_idx_fu_308_p4);
    sensitive << ( c_start_idx );

    SC_METHOD(thread_c_mask_1_fu_625_p3);
    sensitive << ( tmp_27_fu_621_p1 );
    sensitive << ( tmp_i6_fu_611_p4 );

    SC_METHOD(thread_c_mask_fu_302_p2);
    sensitive << ( p_cast1_fu_294_p1 );

    SC_METHOD(thread_c_shift_1_fu_682_p2);
    sensitive << ( c_shift1_fu_104 );

    SC_METHOD(thread_c_shift_2_cast_fu_688_p2);
    sensitive << ( tmp_28_fu_678_p1 );

    SC_METHOD(thread_c_shift_2_fu_702_p3);
    sensitive << ( tmp_29_fu_694_p3 );
    sensitive << ( c_shift_2_cast_fu_688_p2 );

    SC_METHOD(thread_c_shift_3_cast_fu_710_p1);
    sensitive << ( c_shift_2_fu_702_p3 );

    SC_METHOD(thread_c_shift_fu_288_p2);
    sensitive << ( tmp_15_fu_284_p1 );

    SC_METHOD(thread_f_assign_to_int_fu_564_p1);
    sensitive << ( reg_277 );

    SC_METHOD(thread_grp_fdot_3d_fu_244_ap_start);
    sensitive << ( ap_reg_grp_fdot_3d_fu_244_ap_start );

    SC_METHOD(thread_grp_fu_257_opcode);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_5_fu_389_p2 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state38 );

    SC_METHOD(thread_grp_fu_257_p0);
    sensitive << ( reg_277 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( f_assign_3_reg_858 );
    sensitive << ( max_res_reg_198 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state38 );

    SC_METHOD(thread_grp_fu_257_p1);
    sensitive << ( Bias );
    sensitive << ( Beta );
    sensitive << ( Mean );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state38 );

    SC_METHOD(thread_grp_fu_270_opcode);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state43 );

    SC_METHOD(thread_grp_fu_270_p0);
    sensitive << ( reg_277 );
    sensitive << ( grp_fdot_3d_fu_244_ap_return );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state43 );

    SC_METHOD(thread_grp_fu_270_p1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( max_res_1_reg_220 );

    SC_METHOD(thread_i_fu_408_p3);
    sensitive << ( tmp_17_fu_394_p3 );
    sensitive << ( tmp_19_fu_402_p2 );

    SC_METHOD(thread_i_in_1_fu_457_p2);
    sensitive << ( pl_i_assign_reg_188 );

    SC_METHOD(thread_i_in_cast_fu_337_p1);
    sensitive << ( i_in_reg_166 );

    SC_METHOD(thread_j_fu_435_p3);
    sensitive << ( tmp_30_fu_421_p3 );
    sensitive << ( tmp_31_fu_429_p2 );

    SC_METHOD(thread_j_in_1_fu_552_p2);
    sensitive << ( pl_i_assign_1_reg_210 );

    SC_METHOD(thread_j_in_cast_fu_363_p1);
    sensitive << ( j_in_reg_177 );

    SC_METHOD(thread_max_res_1_to_int_fu_480_p1);
    sensitive << ( max_res_1_reg_220 );

    SC_METHOD(thread_notlhs3_fu_498_p2);
    sensitive << ( tmp_32_reg_823 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_11_fu_466_p4 );

    SC_METHOD(thread_notlhs5_fu_516_p2);
    sensitive << ( tmp_32_reg_823 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_12_fu_484_p4 );

    SC_METHOD(thread_notlhs_fu_582_p2);
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( tmp_fu_568_p4 );

    SC_METHOD(thread_notrhs4_fu_504_p2);
    sensitive << ( tmp_32_reg_823 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_33_fu_476_p1 );

    SC_METHOD(thread_notrhs6_fu_522_p2);
    sensitive << ( tmp_32_reg_823 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_34_fu_494_p1 );

    SC_METHOD(thread_notrhs_fu_588_p2);
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( tmp_25_fu_578_p1 );

    SC_METHOD(thread_p_cast1_fu_294_p1);
    sensitive << ( c_shift_fu_288_p2 );

    SC_METHOD(thread_p_cast_fu_298_p1);
    sensitive << ( c_shift_fu_288_p2 );

    SC_METHOD(thread_pl_i_fu_341_p2);
    sensitive << ( i_in_reg_166 );

    SC_METHOD(thread_pl_i_pl_w_cast_fu_359_p1);
    sensitive << ( pl_i_pl_w_fu_353_p2 );

    SC_METHOD(thread_pl_i_pl_w_fu_353_p2);
    sensitive << ( i_in_reg_166 );

    SC_METHOD(thread_pl_j_fu_367_p2);
    sensitive << ( j_in_reg_177 );

    SC_METHOD(thread_pl_j_pl_h_cast_fu_385_p1);
    sensitive << ( pl_j_pl_h_fu_379_p2 );

    SC_METHOD(thread_pl_j_pl_h_fu_379_p2);
    sensitive << ( j_in_reg_177 );

    SC_METHOD(thread_res_2_fu_545_p3);
    sensitive << ( res_reg_832 );
    sensitive << ( max_res_1_reg_220 );
    sensitive << ( tmp_20_fu_540_p2 );

    SC_METHOD(thread_res_to_int_fu_463_p1);
    sensitive << ( res_reg_832 );

    SC_METHOD(thread_tmp_10_fu_444_p2);
    sensitive << ( i_reg_809 );
    sensitive << ( j_fu_435_p3 );

    SC_METHOD(thread_tmp_11_fu_466_p4);
    sensitive << ( res_to_int_fu_463_p1 );

    SC_METHOD(thread_tmp_12_fu_484_p4);
    sensitive << ( max_res_1_to_int_fu_480_p1 );

    SC_METHOD(thread_tmp_13_fu_510_p2);
    sensitive << ( notrhs4_fu_504_p2 );
    sensitive << ( notlhs3_fu_498_p2 );

    SC_METHOD(thread_tmp_14_fu_528_p2);
    sensitive << ( notrhs6_fu_522_p2 );
    sensitive << ( notlhs5_fu_516_p2 );

    SC_METHOD(thread_tmp_15_fu_284_p1);
    sensitive << ( c_start_idx );

    SC_METHOD(thread_tmp_16_fu_534_p2);
    sensitive << ( tmp_13_fu_510_p2 );
    sensitive << ( tmp_14_fu_528_p2 );

    SC_METHOD(thread_tmp_17_fu_394_p3);
    sensitive << ( pl_i_assign_reg_188 );

    SC_METHOD(thread_tmp_19_fu_402_p2);
    sensitive << ( pl_i_assign_reg_188 );

    SC_METHOD(thread_tmp_1_fu_606_p1);
    sensitive << ( c_idx_1_fu_100 );

    SC_METHOD(thread_tmp_20_fu_540_p2);
    sensitive << ( tmp_18_reg_838 );
    sensitive << ( tmp_16_fu_534_p2 );

    SC_METHOD(thread_tmp_25_fu_578_p1);
    sensitive << ( f_assign_to_int_fu_564_p1 );

    SC_METHOD(thread_tmp_26_cast_fu_641_p1);
    sensitive << ( tmp_3_fu_633_p3 );

    SC_METHOD(thread_tmp_26_fu_664_p1);
    sensitive << ( c_shift1_fu_104 );

    SC_METHOD(thread_tmp_27_fu_621_p1);
    sensitive << ( c_mask_2_fu_108 );

    SC_METHOD(thread_tmp_28_fu_678_p1);
    sensitive << ( c_shift1_fu_104 );

    SC_METHOD(thread_tmp_29_fu_694_p3);
    sensitive << ( c_shift_1_fu_682_p2 );

    SC_METHOD(thread_tmp_30_fu_421_p3);
    sensitive << ( pl_i_assign_1_reg_210 );

    SC_METHOD(thread_tmp_31_fu_429_p2);
    sensitive << ( pl_i_assign_1_reg_210 );

    SC_METHOD(thread_tmp_32_fu_449_p3);
    sensitive << ( tmp_10_fu_444_p2 );

    SC_METHOD(thread_tmp_33_fu_476_p1);
    sensitive << ( res_to_int_fu_463_p1 );

    SC_METHOD(thread_tmp_34_fu_494_p1);
    sensitive << ( max_res_1_to_int_fu_480_p1 );

    SC_METHOD(thread_tmp_3_fu_633_p3);
    sensitive << ( tmp_27_fu_621_p1 );

    SC_METHOD(thread_tmp_4_fu_373_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( pl_j_fu_367_p2 );

    SC_METHOD(thread_tmp_5_fu_389_p2);
    sensitive << ( pl_i_pl_w_cast_reg_783 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( pl_i_assign_reg_188 );

    SC_METHOD(thread_tmp_6_fu_594_p2);
    sensitive << ( notrhs_fu_588_p2 );
    sensitive << ( notlhs_fu_582_p2 );

    SC_METHOD(thread_tmp_8_fu_600_p2);
    sensitive << ( grp_fu_270_p2 );
    sensitive << ( tmp_6_fu_594_p2 );

    SC_METHOD(thread_tmp_9_fu_416_p2);
    sensitive << ( pl_j_pl_h_cast_reg_801 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( pl_i_assign_1_reg_210 );

    SC_METHOD(thread_tmp_fu_568_p4);
    sensitive << ( f_assign_to_int_fu_564_p1 );

    SC_METHOD(thread_tmp_i6_fu_611_p4);
    sensitive << ( c_mask_2_fu_108 );

    SC_METHOD(thread_tmp_s_fu_347_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( pl_i_fu_341_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_s_fu_347_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_4_fu_373_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_5_fu_389_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_9_fu_416_p2 );
    sensitive << ( tmp_32_fu_449_p3 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_fdot_3d_fu_244_ap_done );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "00000000000000000000000000000000000000000001";
    ap_reg_grp_fdot_3d_fu_244_ap_start = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "fconv_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, A_address0, "(port)A_address0");
    sc_trace(mVcdFile, A_ce0, "(port)A_ce0");
    sc_trace(mVcdFile, A_q0, "(port)A_q0");
    sc_trace(mVcdFile, F_offset, "(port)F_offset");
    sc_trace(mVcdFile, C_address0, "(port)C_address0");
    sc_trace(mVcdFile, C_ce0, "(port)C_ce0");
    sc_trace(mVcdFile, C_we0, "(port)C_we0");
    sc_trace(mVcdFile, C_d0, "(port)C_d0");
    sc_trace(mVcdFile, C_q0, "(port)C_q0");
    sc_trace(mVcdFile, c_start_idx, "(port)c_start_idx");
    sc_trace(mVcdFile, Bias, "(port)Bias");
    sc_trace(mVcdFile, Gamma, "(port)Gamma");
    sc_trace(mVcdFile, Beta, "(port)Beta");
    sc_trace(mVcdFile, Mean, "(port)Mean");
    sc_trace(mVcdFile, Std, "(port)Std");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, grp_fu_257_p2, "grp_fu_257_p2");
    sc_trace(mVcdFile, reg_277, "reg_277");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, ap_CS_fsm_state42, "ap_CS_fsm_state42");
    sc_trace(mVcdFile, i_in_cast_fu_337_p1, "i_in_cast_fu_337_p1");
    sc_trace(mVcdFile, i_in_cast_reg_770, "i_in_cast_reg_770");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, pl_i_fu_341_p2, "pl_i_fu_341_p2");
    sc_trace(mVcdFile, pl_i_reg_775, "pl_i_reg_775");
    sc_trace(mVcdFile, pl_i_pl_w_cast_fu_359_p1, "pl_i_pl_w_cast_fu_359_p1");
    sc_trace(mVcdFile, pl_i_pl_w_cast_reg_783, "pl_i_pl_w_cast_reg_783");
    sc_trace(mVcdFile, tmp_s_fu_347_p2, "tmp_s_fu_347_p2");
    sc_trace(mVcdFile, j_in_cast_fu_363_p1, "j_in_cast_fu_363_p1");
    sc_trace(mVcdFile, j_in_cast_reg_788, "j_in_cast_reg_788");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, pl_j_fu_367_p2, "pl_j_fu_367_p2");
    sc_trace(mVcdFile, pl_j_reg_793, "pl_j_reg_793");
    sc_trace(mVcdFile, pl_j_pl_h_cast_fu_385_p1, "pl_j_pl_h_cast_fu_385_p1");
    sc_trace(mVcdFile, pl_j_pl_h_cast_reg_801, "pl_j_pl_h_cast_reg_801");
    sc_trace(mVcdFile, tmp_4_fu_373_p2, "tmp_4_fu_373_p2");
    sc_trace(mVcdFile, i_fu_408_p3, "i_fu_408_p3");
    sc_trace(mVcdFile, i_reg_809, "i_reg_809");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_5_fu_389_p2, "tmp_5_fu_389_p2");
    sc_trace(mVcdFile, j_fu_435_p3, "j_fu_435_p3");
    sc_trace(mVcdFile, j_reg_818, "j_reg_818");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_9_fu_416_p2, "tmp_9_fu_416_p2");
    sc_trace(mVcdFile, tmp_32_fu_449_p3, "tmp_32_fu_449_p3");
    sc_trace(mVcdFile, tmp_32_reg_823, "tmp_32_reg_823");
    sc_trace(mVcdFile, i_in_1_fu_457_p2, "i_in_1_fu_457_p2");
    sc_trace(mVcdFile, grp_fdot_3d_fu_244_ap_return, "grp_fdot_3d_fu_244_ap_return");
    sc_trace(mVcdFile, res_reg_832, "res_reg_832");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, grp_fdot_3d_fu_244_ap_done, "grp_fdot_3d_fu_244_ap_done");
    sc_trace(mVcdFile, grp_fu_270_p2, "grp_fu_270_p2");
    sc_trace(mVcdFile, tmp_18_reg_838, "tmp_18_reg_838");
    sc_trace(mVcdFile, res_2_fu_545_p3, "res_2_fu_545_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, j_in_1_fu_552_p2, "j_in_1_fu_552_p2");
    sc_trace(mVcdFile, j_in_1_reg_848, "j_in_1_reg_848");
    sc_trace(mVcdFile, grp_fu_266_p2, "grp_fu_266_p2");
    sc_trace(mVcdFile, f_assign_2_reg_853, "f_assign_2_reg_853");
    sc_trace(mVcdFile, ap_CS_fsm_state33, "ap_CS_fsm_state33");
    sc_trace(mVcdFile, grp_fu_262_p2, "grp_fu_262_p2");
    sc_trace(mVcdFile, f_assign_3_reg_858, "f_assign_3_reg_858");
    sc_trace(mVcdFile, ap_CS_fsm_state37, "ap_CS_fsm_state37");
    sc_trace(mVcdFile, tmp_8_fu_600_p2, "tmp_8_fu_600_p2");
    sc_trace(mVcdFile, tmp_8_reg_863, "tmp_8_reg_863");
    sc_trace(mVcdFile, ap_CS_fsm_state43, "ap_CS_fsm_state43");
    sc_trace(mVcdFile, C_addr_reg_868, "C_addr_reg_868");
    sc_trace(mVcdFile, grp_fdot_3d_fu_244_ap_start, "grp_fdot_3d_fu_244_ap_start");
    sc_trace(mVcdFile, grp_fdot_3d_fu_244_ap_idle, "grp_fdot_3d_fu_244_ap_idle");
    sc_trace(mVcdFile, grp_fdot_3d_fu_244_ap_ready, "grp_fdot_3d_fu_244_ap_ready");
    sc_trace(mVcdFile, grp_fdot_3d_fu_244_A_address0, "grp_fdot_3d_fu_244_A_address0");
    sc_trace(mVcdFile, grp_fdot_3d_fu_244_A_ce0, "grp_fdot_3d_fu_244_A_ce0");
    sc_trace(mVcdFile, i_in_reg_166, "i_in_reg_166");
    sc_trace(mVcdFile, j_in_reg_177, "j_in_reg_177");
    sc_trace(mVcdFile, ap_CS_fsm_state44, "ap_CS_fsm_state44");
    sc_trace(mVcdFile, pl_i_assign_reg_188, "pl_i_assign_reg_188");
    sc_trace(mVcdFile, max_res_reg_198, "max_res_reg_198");
    sc_trace(mVcdFile, pl_i_assign_1_reg_210, "pl_i_assign_1_reg_210");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, max_res_1_reg_220, "max_res_1_reg_220");
    sc_trace(mVcdFile, max_res_2_reg_232, "max_res_2_reg_232");
    sc_trace(mVcdFile, ap_reg_grp_fdot_3d_fu_244_ap_start, "ap_reg_grp_fdot_3d_fu_244_ap_start");
    sc_trace(mVcdFile, tmp_1_fu_606_p1, "tmp_1_fu_606_p1");
    sc_trace(mVcdFile, c_idx_1_fu_100, "c_idx_1_fu_100");
    sc_trace(mVcdFile, c_idx_cast_fu_318_p1, "c_idx_cast_fu_318_p1");
    sc_trace(mVcdFile, c_idx_2_fu_645_p2, "c_idx_2_fu_645_p2");
    sc_trace(mVcdFile, c_shift1_fu_104, "c_shift1_fu_104");
    sc_trace(mVcdFile, p_cast_fu_298_p1, "p_cast_fu_298_p1");
    sc_trace(mVcdFile, c_shift_3_cast_fu_710_p1, "c_shift_3_cast_fu_710_p1");
    sc_trace(mVcdFile, c_mask_2_fu_108, "c_mask_2_fu_108");
    sc_trace(mVcdFile, c_mask_fu_302_p2, "c_mask_fu_302_p2");
    sc_trace(mVcdFile, c_mask_1_fu_625_p3, "c_mask_1_fu_625_p3");
    sc_trace(mVcdFile, grp_fu_257_p0, "grp_fu_257_p0");
    sc_trace(mVcdFile, grp_fu_257_p1, "grp_fu_257_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state38, "ap_CS_fsm_state38");
    sc_trace(mVcdFile, ap_CS_fsm_state34, "ap_CS_fsm_state34");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, grp_fu_270_p0, "grp_fu_270_p0");
    sc_trace(mVcdFile, grp_fu_270_p1, "grp_fu_270_p1");
    sc_trace(mVcdFile, tmp_15_fu_284_p1, "tmp_15_fu_284_p1");
    sc_trace(mVcdFile, c_shift_fu_288_p2, "c_shift_fu_288_p2");
    sc_trace(mVcdFile, p_cast1_fu_294_p1, "p_cast1_fu_294_p1");
    sc_trace(mVcdFile, c_idx_fu_308_p4, "c_idx_fu_308_p4");
    sc_trace(mVcdFile, pl_i_pl_w_fu_353_p2, "pl_i_pl_w_fu_353_p2");
    sc_trace(mVcdFile, pl_j_pl_h_fu_379_p2, "pl_j_pl_h_fu_379_p2");
    sc_trace(mVcdFile, tmp_17_fu_394_p3, "tmp_17_fu_394_p3");
    sc_trace(mVcdFile, tmp_19_fu_402_p2, "tmp_19_fu_402_p2");
    sc_trace(mVcdFile, tmp_30_fu_421_p3, "tmp_30_fu_421_p3");
    sc_trace(mVcdFile, tmp_31_fu_429_p2, "tmp_31_fu_429_p2");
    sc_trace(mVcdFile, tmp_10_fu_444_p2, "tmp_10_fu_444_p2");
    sc_trace(mVcdFile, res_to_int_fu_463_p1, "res_to_int_fu_463_p1");
    sc_trace(mVcdFile, max_res_1_to_int_fu_480_p1, "max_res_1_to_int_fu_480_p1");
    sc_trace(mVcdFile, tmp_11_fu_466_p4, "tmp_11_fu_466_p4");
    sc_trace(mVcdFile, tmp_33_fu_476_p1, "tmp_33_fu_476_p1");
    sc_trace(mVcdFile, notrhs4_fu_504_p2, "notrhs4_fu_504_p2");
    sc_trace(mVcdFile, notlhs3_fu_498_p2, "notlhs3_fu_498_p2");
    sc_trace(mVcdFile, tmp_12_fu_484_p4, "tmp_12_fu_484_p4");
    sc_trace(mVcdFile, tmp_34_fu_494_p1, "tmp_34_fu_494_p1");
    sc_trace(mVcdFile, notrhs6_fu_522_p2, "notrhs6_fu_522_p2");
    sc_trace(mVcdFile, notlhs5_fu_516_p2, "notlhs5_fu_516_p2");
    sc_trace(mVcdFile, tmp_13_fu_510_p2, "tmp_13_fu_510_p2");
    sc_trace(mVcdFile, tmp_14_fu_528_p2, "tmp_14_fu_528_p2");
    sc_trace(mVcdFile, tmp_16_fu_534_p2, "tmp_16_fu_534_p2");
    sc_trace(mVcdFile, tmp_20_fu_540_p2, "tmp_20_fu_540_p2");
    sc_trace(mVcdFile, f_assign_to_int_fu_564_p1, "f_assign_to_int_fu_564_p1");
    sc_trace(mVcdFile, tmp_fu_568_p4, "tmp_fu_568_p4");
    sc_trace(mVcdFile, tmp_25_fu_578_p1, "tmp_25_fu_578_p1");
    sc_trace(mVcdFile, notrhs_fu_588_p2, "notrhs_fu_588_p2");
    sc_trace(mVcdFile, notlhs_fu_582_p2, "notlhs_fu_582_p2");
    sc_trace(mVcdFile, tmp_6_fu_594_p2, "tmp_6_fu_594_p2");
    sc_trace(mVcdFile, tmp_27_fu_621_p1, "tmp_27_fu_621_p1");
    sc_trace(mVcdFile, tmp_i6_fu_611_p4, "tmp_i6_fu_611_p4");
    sc_trace(mVcdFile, tmp_3_fu_633_p3, "tmp_3_fu_633_p3");
    sc_trace(mVcdFile, tmp_26_cast_fu_641_p1, "tmp_26_cast_fu_641_p1");
    sc_trace(mVcdFile, tmp_26_fu_664_p1, "tmp_26_fu_664_p1");
    sc_trace(mVcdFile, tmp_28_fu_678_p1, "tmp_28_fu_678_p1");
    sc_trace(mVcdFile, c_shift_1_fu_682_p2, "c_shift_1_fu_682_p2");
    sc_trace(mVcdFile, tmp_29_fu_694_p3, "tmp_29_fu_694_p3");
    sc_trace(mVcdFile, c_shift_2_cast_fu_688_p2, "c_shift_2_cast_fu_688_p2");
    sc_trace(mVcdFile, c_shift_2_fu_702_p3, "c_shift_2_fu_702_p3");
    sc_trace(mVcdFile, grp_fu_257_opcode, "grp_fu_257_opcode");
    sc_trace(mVcdFile, grp_fu_270_opcode, "grp_fu_270_opcode");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

fconv::~fconv() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_fdot_3d_fu_244;
    delete ebnn_compute_fadddEe_U9;
    delete ebnn_compute_fmuleOg_U10;
    delete ebnn_compute_fdivfYi_U11;
    delete ebnn_compute_fcmpg8j_U12;
}

void fconv::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void fconv::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_fdot_3d_fu_244_ap_start = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, tmp_9_fu_416_p2.read()) && 
             esl_seteq<1,1,1>(tmp_32_fu_449_p3.read(), ap_const_lv1_0))) {
            ap_reg_grp_fdot_3d_fu_244_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_fdot_3d_fu_244_ap_ready.read())) {
            ap_reg_grp_fdot_3d_fu_244_ap_start = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        c_idx_1_fu_100 = c_idx_2_fu_645_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        c_idx_1_fu_100 = c_idx_cast_fu_318_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        c_mask_2_fu_108 = c_mask_1_fu_625_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        c_mask_2_fu_108 = c_mask_fu_302_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read())) {
        c_shift1_fu_104 = c_shift_3_cast_fu_710_p1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        c_shift1_fu_104 = p_cast_fu_298_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(tmp_4_fu_373_p2.read(), ap_const_lv1_0))) {
        i_in_reg_166 = pl_i_reg_775.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_in_reg_166 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_s_fu_347_p2.read(), ap_const_lv1_1))) {
        j_in_reg_177 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read())) {
        j_in_reg_177 = pl_j_reg_793.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        max_res_1_reg_220 = max_res_2_reg_232.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_5_fu_389_p2.read()))) {
        max_res_1_reg_220 = max_res_reg_198.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_9_fu_416_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_32_fu_449_p3.read()))) {
        max_res_2_reg_232 = max_res_1_reg_220.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(tmp_32_reg_823.read(), ap_const_lv1_0))) {
        max_res_2_reg_232 = res_2_fu_545_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(tmp_9_fu_416_p2.read(), ap_const_lv1_0))) {
        max_res_reg_198 = max_res_1_reg_220.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_4_fu_373_p2.read()))) {
        max_res_reg_198 = ap_const_lv32_FF7FFFFF;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        pl_i_assign_1_reg_210 = j_in_1_reg_848.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_5_fu_389_p2.read()))) {
        pl_i_assign_1_reg_210 = j_in_cast_reg_788.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(tmp_9_fu_416_p2.read(), ap_const_lv1_0))) {
        pl_i_assign_reg_188 = i_in_1_fu_457_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_4_fu_373_p2.read()))) {
        pl_i_assign_reg_188 = i_in_cast_reg_770.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        C_addr_reg_868 =  (sc_lv<7>) (tmp_1_fu_606_p1.read());
        tmp_8_reg_863 = tmp_8_fu_600_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state33.read())) {
        f_assign_2_reg_853 = grp_fu_266_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state37.read())) {
        f_assign_3_reg_858 = grp_fu_262_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_in_cast_reg_770 = i_in_cast_fu_337_p1.read();
        pl_i_reg_775 = pl_i_fu_341_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_5_fu_389_p2.read()))) {
        i_reg_809 = i_fu_408_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        j_in_1_reg_848 = j_in_1_fu_552_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        j_in_cast_reg_788 = j_in_cast_fu_363_p1.read();
        pl_j_reg_793 = pl_j_fu_367_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_9_fu_416_p2.read()))) {
        j_reg_818 = j_fu_435_p3.read();
        tmp_32_reg_823 = tmp_10_fu_444_p2.read().range(31, 31);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_s_fu_347_p2.read(), ap_const_lv1_1))) {
        pl_i_pl_w_cast_reg_783 = pl_i_pl_w_cast_fu_359_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_4_fu_373_p2.read()))) {
        pl_j_pl_h_cast_reg_801 = pl_j_pl_h_cast_fu_385_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read()))) {
        reg_277 = grp_fu_257_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(grp_fdot_3d_fu_244_ap_done.read(), ap_const_logic_1))) {
        res_reg_832 = grp_fdot_3d_fu_244_ap_return.read();
        tmp_18_reg_838 = grp_fu_270_p2.read();
    }
}

void fconv::thread_A_address0() {
    A_address0 = grp_fdot_3d_fu_244_A_address0.read();
}

void fconv::thread_A_ce0() {
    A_ce0 = grp_fdot_3d_fu_244_A_ce0.read();
}

void fconv::thread_C_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read())) {
        C_address0 = C_addr_reg_868.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        C_address0 =  (sc_lv<7>) (tmp_1_fu_606_p1.read());
    } else {
        C_address0 = "XXXXXXX";
    }
}

void fconv::thread_C_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read()))) {
        C_ce0 = ap_const_logic_1;
    } else {
        C_ce0 = ap_const_logic_0;
    }
}

void fconv::thread_C_d0() {
    C_d0 = esl_bitset<8,8,8,1>(C_q0.read(), tmp_26_fu_664_p1.read(), tmp_8_reg_863.read());
}

void fconv::thread_C_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read())) {
        C_we0 = ap_const_logic_1;
    } else {
        C_we0 = ap_const_logic_0;
    }
}

void fconv::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void fconv::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void fconv::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void fconv::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void fconv::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void fconv::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void fconv::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void fconv::thread_ap_CS_fsm_state33() {
    ap_CS_fsm_state33 = ap_CS_fsm.read()[32];
}

void fconv::thread_ap_CS_fsm_state34() {
    ap_CS_fsm_state34 = ap_CS_fsm.read()[33];
}

void fconv::thread_ap_CS_fsm_state37() {
    ap_CS_fsm_state37 = ap_CS_fsm.read()[36];
}

void fconv::thread_ap_CS_fsm_state38() {
    ap_CS_fsm_state38 = ap_CS_fsm.read()[37];
}

void fconv::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void fconv::thread_ap_CS_fsm_state42() {
    ap_CS_fsm_state42 = ap_CS_fsm.read()[41];
}

void fconv::thread_ap_CS_fsm_state43() {
    ap_CS_fsm_state43 = ap_CS_fsm.read()[42];
}

void fconv::thread_ap_CS_fsm_state44() {
    ap_CS_fsm_state44 = ap_CS_fsm.read()[43];
}

void fconv::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void fconv::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void fconv::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void fconv::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void fconv::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(tmp_s_fu_347_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void fconv::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void fconv::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_s_fu_347_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void fconv::thread_c_idx_2_fu_645_p2() {
    c_idx_2_fu_645_p2 = (!c_idx_1_fu_100.read().is_01() || !tmp_26_cast_fu_641_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(c_idx_1_fu_100.read()) + sc_biguint<32>(tmp_26_cast_fu_641_p1.read()));
}

void fconv::thread_c_idx_cast_fu_318_p1() {
    c_idx_cast_fu_318_p1 = esl_zext<32,6>(c_idx_fu_308_p4.read());
}

void fconv::thread_c_idx_fu_308_p4() {
    c_idx_fu_308_p4 = c_start_idx.read().range(8, 3);
}

void fconv::thread_c_mask_1_fu_625_p3() {
    c_mask_1_fu_625_p3 = esl_concat<1,7>(tmp_27_fu_621_p1.read(), tmp_i6_fu_611_p4.read());
}

void fconv::thread_c_mask_fu_302_p2() {
    c_mask_fu_302_p2 = (!p_cast1_fu_294_p1.read().is_01())? sc_lv<8>(): ap_const_lv8_1 << (unsigned short)p_cast1_fu_294_p1.read().to_uint();
}

void fconv::thread_c_shift_1_fu_682_p2() {
    c_shift_1_fu_682_p2 = (!ap_const_lv32_FFFFFFFF.is_01() || !c_shift1_fu_104.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFFF) + sc_biguint<32>(c_shift1_fu_104.read()));
}

void fconv::thread_c_shift_2_cast_fu_688_p2() {
    c_shift_2_cast_fu_688_p2 = (!ap_const_lv31_7FFFFFFF.is_01() || !tmp_28_fu_678_p1.read().is_01())? sc_lv<31>(): (sc_bigint<31>(ap_const_lv31_7FFFFFFF) + sc_biguint<31>(tmp_28_fu_678_p1.read()));
}

void fconv::thread_c_shift_2_fu_702_p3() {
    c_shift_2_fu_702_p3 = (!tmp_29_fu_694_p3.read()[0].is_01())? sc_lv<31>(): ((tmp_29_fu_694_p3.read()[0].to_bool())? ap_const_lv31_7: c_shift_2_cast_fu_688_p2.read());
}

void fconv::thread_c_shift_3_cast_fu_710_p1() {
    c_shift_3_cast_fu_710_p1 = esl_zext<32,31>(c_shift_2_fu_702_p3.read());
}

void fconv::thread_c_shift_fu_288_p2() {
    c_shift_fu_288_p2 = (tmp_15_fu_284_p1.read() ^ ap_const_lv3_7);
}

void fconv::thread_f_assign_to_int_fu_564_p1() {
    f_assign_to_int_fu_564_p1 = reg_277.read();
}

void fconv::thread_grp_fdot_3d_fu_244_ap_start() {
    grp_fdot_3d_fu_244_ap_start = ap_reg_grp_fdot_3d_fu_244_ap_start.read();
}

void fconv::thread_grp_fu_257_opcode() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        grp_fu_257_opcode = ap_const_lv2_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state38.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                 esl_seteq<1,1,1>(tmp_5_fu_389_p2.read(), ap_const_lv1_0)))) {
        grp_fu_257_opcode = ap_const_lv2_0;
    } else {
        grp_fu_257_opcode =  (sc_lv<2>) ("XX");
    }
}

void fconv::thread_grp_fu_257_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state38.read())) {
        grp_fu_257_p0 = f_assign_3_reg_858.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        grp_fu_257_p0 = reg_277.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        grp_fu_257_p0 = max_res_reg_198.read();
    } else {
        grp_fu_257_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void fconv::thread_grp_fu_257_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state38.read())) {
        grp_fu_257_p1 = Beta.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        grp_fu_257_p1 = Mean.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        grp_fu_257_p1 = Bias.read();
    } else {
        grp_fu_257_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void fconv::thread_grp_fu_270_opcode() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        grp_fu_270_opcode = ap_const_lv5_3;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        grp_fu_270_opcode = ap_const_lv5_2;
    } else {
        grp_fu_270_opcode =  (sc_lv<5>) ("XXXXX");
    }
}

void fconv::thread_grp_fu_270_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        grp_fu_270_p0 = reg_277.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        grp_fu_270_p0 = grp_fdot_3d_fu_244_ap_return.read();
    } else {
        grp_fu_270_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void fconv::thread_grp_fu_270_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        grp_fu_270_p1 = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        grp_fu_270_p1 = max_res_1_reg_220.read();
    } else {
        grp_fu_270_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void fconv::thread_i_fu_408_p3() {
    i_fu_408_p3 = (!tmp_17_fu_394_p3.read()[0].is_01())? sc_lv<32>(): ((tmp_17_fu_394_p3.read()[0].to_bool())? ap_const_lv32_80000001: tmp_19_fu_402_p2.read());
}

void fconv::thread_i_in_1_fu_457_p2() {
    i_in_1_fu_457_p2 = (!pl_i_assign_reg_188.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(pl_i_assign_reg_188.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void fconv::thread_i_in_cast_fu_337_p1() {
    i_in_cast_fu_337_p1 = esl_zext<32,4>(i_in_reg_166.read());
}

void fconv::thread_j_fu_435_p3() {
    j_fu_435_p3 = (!tmp_30_fu_421_p3.read()[0].is_01())? sc_lv<32>(): ((tmp_30_fu_421_p3.read()[0].to_bool())? ap_const_lv32_80000001: tmp_31_fu_429_p2.read());
}

void fconv::thread_j_in_1_fu_552_p2() {
    j_in_1_fu_552_p2 = (!pl_i_assign_1_reg_210.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(pl_i_assign_1_reg_210.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void fconv::thread_j_in_cast_fu_363_p1() {
    j_in_cast_fu_363_p1 = esl_zext<32,4>(j_in_reg_177.read());
}

void fconv::thread_max_res_1_to_int_fu_480_p1() {
    max_res_1_to_int_fu_480_p1 = max_res_1_reg_220.read();
}

void fconv::thread_notlhs3_fu_498_p2() {
    notlhs3_fu_498_p2 = (!tmp_11_fu_466_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_11_fu_466_p4.read() != ap_const_lv8_FF);
}

void fconv::thread_notlhs5_fu_516_p2() {
    notlhs5_fu_516_p2 = (!tmp_12_fu_484_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_12_fu_484_p4.read() != ap_const_lv8_FF);
}

void fconv::thread_notlhs_fu_582_p2() {
    notlhs_fu_582_p2 = (!tmp_fu_568_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_fu_568_p4.read() != ap_const_lv8_FF);
}

void fconv::thread_notrhs4_fu_504_p2() {
    notrhs4_fu_504_p2 = (!tmp_33_fu_476_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_33_fu_476_p1.read() == ap_const_lv23_0);
}

void fconv::thread_notrhs6_fu_522_p2() {
    notrhs6_fu_522_p2 = (!tmp_34_fu_494_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_34_fu_494_p1.read() == ap_const_lv23_0);
}

void fconv::thread_notrhs_fu_588_p2() {
    notrhs_fu_588_p2 = (!tmp_25_fu_578_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_25_fu_578_p1.read() == ap_const_lv23_0);
}

void fconv::thread_p_cast1_fu_294_p1() {
    p_cast1_fu_294_p1 = esl_zext<8,3>(c_shift_fu_288_p2.read());
}

void fconv::thread_p_cast_fu_298_p1() {
    p_cast_fu_298_p1 = esl_zext<32,3>(c_shift_fu_288_p2.read());
}

void fconv::thread_pl_i_fu_341_p2() {
    pl_i_fu_341_p2 = (!i_in_reg_166.read().is_01() || !ap_const_lv4_2.is_01())? sc_lv<4>(): (sc_biguint<4>(i_in_reg_166.read()) + sc_biguint<4>(ap_const_lv4_2));
}

void fconv::thread_pl_i_pl_w_cast_fu_359_p1() {
    pl_i_pl_w_cast_fu_359_p1 = esl_zext<32,4>(pl_i_pl_w_fu_353_p2.read());
}

void fconv::thread_pl_i_pl_w_fu_353_p2() {
    pl_i_pl_w_fu_353_p2 = (!i_in_reg_166.read().is_01() || !ap_const_lv4_3.is_01())? sc_lv<4>(): (sc_biguint<4>(i_in_reg_166.read()) + sc_biguint<4>(ap_const_lv4_3));
}

void fconv::thread_pl_j_fu_367_p2() {
    pl_j_fu_367_p2 = (!j_in_reg_177.read().is_01() || !ap_const_lv4_2.is_01())? sc_lv<4>(): (sc_biguint<4>(j_in_reg_177.read()) + sc_biguint<4>(ap_const_lv4_2));
}

void fconv::thread_pl_j_pl_h_cast_fu_385_p1() {
    pl_j_pl_h_cast_fu_385_p1 = esl_zext<32,4>(pl_j_pl_h_fu_379_p2.read());
}

void fconv::thread_pl_j_pl_h_fu_379_p2() {
    pl_j_pl_h_fu_379_p2 = (!j_in_reg_177.read().is_01() || !ap_const_lv4_3.is_01())? sc_lv<4>(): (sc_biguint<4>(j_in_reg_177.read()) + sc_biguint<4>(ap_const_lv4_3));
}

void fconv::thread_res_2_fu_545_p3() {
    res_2_fu_545_p3 = (!tmp_20_fu_540_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_20_fu_540_p2.read()[0].to_bool())? res_reg_832.read(): max_res_1_reg_220.read());
}

void fconv::thread_res_to_int_fu_463_p1() {
    res_to_int_fu_463_p1 = res_reg_832.read();
}

void fconv::thread_tmp_10_fu_444_p2() {
    tmp_10_fu_444_p2 = (j_fu_435_p3.read() | i_reg_809.read());
}

void fconv::thread_tmp_11_fu_466_p4() {
    tmp_11_fu_466_p4 = res_to_int_fu_463_p1.read().range(30, 23);
}

void fconv::thread_tmp_12_fu_484_p4() {
    tmp_12_fu_484_p4 = max_res_1_to_int_fu_480_p1.read().range(30, 23);
}

void fconv::thread_tmp_13_fu_510_p2() {
    tmp_13_fu_510_p2 = (notrhs4_fu_504_p2.read() | notlhs3_fu_498_p2.read());
}

void fconv::thread_tmp_14_fu_528_p2() {
    tmp_14_fu_528_p2 = (notrhs6_fu_522_p2.read() | notlhs5_fu_516_p2.read());
}

void fconv::thread_tmp_15_fu_284_p1() {
    tmp_15_fu_284_p1 = c_start_idx.read().range(3-1, 0);
}

void fconv::thread_tmp_16_fu_534_p2() {
    tmp_16_fu_534_p2 = (tmp_13_fu_510_p2.read() & tmp_14_fu_528_p2.read());
}

void fconv::thread_tmp_17_fu_394_p3() {
    tmp_17_fu_394_p3 = pl_i_assign_reg_188.read().range(31, 31);
}

void fconv::thread_tmp_19_fu_402_p2() {
    tmp_19_fu_402_p2 = (!ap_const_lv32_1.is_01())? sc_lv<32>(): pl_i_assign_reg_188.read() << (unsigned short)ap_const_lv32_1.to_uint();
}

void fconv::thread_tmp_1_fu_606_p1() {
    tmp_1_fu_606_p1 = esl_sext<64,32>(c_idx_1_fu_100.read());
}

void fconv::thread_tmp_20_fu_540_p2() {
    tmp_20_fu_540_p2 = (tmp_16_fu_534_p2.read() & tmp_18_reg_838.read());
}

void fconv::thread_tmp_25_fu_578_p1() {
    tmp_25_fu_578_p1 = f_assign_to_int_fu_564_p1.read().range(23-1, 0);
}

void fconv::thread_tmp_26_cast_fu_641_p1() {
    tmp_26_cast_fu_641_p1 = esl_zext<32,8>(tmp_3_fu_633_p3.read());
}

void fconv::thread_tmp_26_fu_664_p1() {
    tmp_26_fu_664_p1 = c_shift1_fu_104.read().range(8-1, 0);
}

void fconv::thread_tmp_27_fu_621_p1() {
    tmp_27_fu_621_p1 = c_mask_2_fu_108.read().range(1-1, 0);
}

void fconv::thread_tmp_28_fu_678_p1() {
    tmp_28_fu_678_p1 = c_shift1_fu_104.read().range(31-1, 0);
}

void fconv::thread_tmp_29_fu_694_p3() {
    tmp_29_fu_694_p3 = c_shift_1_fu_682_p2.read().range(31, 31);
}

void fconv::thread_tmp_30_fu_421_p3() {
    tmp_30_fu_421_p3 = pl_i_assign_1_reg_210.read().range(31, 31);
}

void fconv::thread_tmp_31_fu_429_p2() {
    tmp_31_fu_429_p2 = (!ap_const_lv32_1.is_01())? sc_lv<32>(): pl_i_assign_1_reg_210.read() << (unsigned short)ap_const_lv32_1.to_uint();
}

void fconv::thread_tmp_32_fu_449_p3() {
    tmp_32_fu_449_p3 = tmp_10_fu_444_p2.read().range(31, 31);
}

void fconv::thread_tmp_33_fu_476_p1() {
    tmp_33_fu_476_p1 = res_to_int_fu_463_p1.read().range(23-1, 0);
}

void fconv::thread_tmp_34_fu_494_p1() {
    tmp_34_fu_494_p1 = max_res_1_to_int_fu_480_p1.read().range(23-1, 0);
}

void fconv::thread_tmp_3_fu_633_p3() {
    tmp_3_fu_633_p3 = esl_concat<7,1>(ap_const_lv7_0, tmp_27_fu_621_p1.read());
}

void fconv::thread_tmp_4_fu_373_p2() {
    tmp_4_fu_373_p2 = (!pl_j_fu_367_p2.read().is_01() || !ap_const_lv4_D.is_01())? sc_lv<1>(): (sc_biguint<4>(pl_j_fu_367_p2.read()) < sc_biguint<4>(ap_const_lv4_D));
}

void fconv::thread_tmp_5_fu_389_p2() {
    tmp_5_fu_389_p2 = (!pl_i_assign_reg_188.read().is_01() || !pl_i_pl_w_cast_reg_783.read().is_01())? sc_lv<1>(): (sc_bigint<32>(pl_i_assign_reg_188.read()) < sc_bigint<32>(pl_i_pl_w_cast_reg_783.read()));
}

void fconv::thread_tmp_6_fu_594_p2() {
    tmp_6_fu_594_p2 = (notrhs_fu_588_p2.read() | notlhs_fu_582_p2.read());
}

void fconv::thread_tmp_8_fu_600_p2() {
    tmp_8_fu_600_p2 = (tmp_6_fu_594_p2.read() & grp_fu_270_p2.read());
}

void fconv::thread_tmp_9_fu_416_p2() {
    tmp_9_fu_416_p2 = (!pl_i_assign_1_reg_210.read().is_01() || !pl_j_pl_h_cast_reg_801.read().is_01())? sc_lv<1>(): (sc_bigint<32>(pl_i_assign_1_reg_210.read()) < sc_bigint<32>(pl_j_pl_h_cast_reg_801.read()));
}

void fconv::thread_tmp_fu_568_p4() {
    tmp_fu_568_p4 = f_assign_to_int_fu_564_p1.read().range(30, 23);
}

void fconv::thread_tmp_i6_fu_611_p4() {
    tmp_i6_fu_611_p4 = c_mask_2_fu_108.read().range(7, 1);
}

void fconv::thread_tmp_s_fu_347_p2() {
    tmp_s_fu_347_p2 = (!pl_i_fu_341_p2.read().is_01() || !ap_const_lv4_D.is_01())? sc_lv<1>(): (sc_biguint<4>(pl_i_fu_341_p2.read()) < sc_biguint<4>(ap_const_lv4_D));
}

void fconv::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_s_fu_347_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(tmp_4_fu_373_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_5_fu_389_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(tmp_9_fu_416_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_9_fu_416_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_32_fu_449_p3.read()))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(grp_fdot_3d_fu_244_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state30;
            break;
        case 536870912 : 
            ap_NS_fsm = ap_ST_fsm_state31;
            break;
        case 1073741824 : 
            ap_NS_fsm = ap_ST_fsm_state32;
            break;
        case 2147483648 : 
            ap_NS_fsm = ap_ST_fsm_state33;
            break;
        case 4294967296 : 
            ap_NS_fsm = ap_ST_fsm_state34;
            break;
        case 8589934592 : 
            ap_NS_fsm = ap_ST_fsm_state35;
            break;
        case 17179869184 : 
            ap_NS_fsm = ap_ST_fsm_state36;
            break;
        case 34359738368 : 
            ap_NS_fsm = ap_ST_fsm_state37;
            break;
        case 68719476736 : 
            ap_NS_fsm = ap_ST_fsm_state38;
            break;
        case 137438953472 : 
            ap_NS_fsm = ap_ST_fsm_state39;
            break;
        case 274877906944 : 
            ap_NS_fsm = ap_ST_fsm_state40;
            break;
        case 549755813888 : 
            ap_NS_fsm = ap_ST_fsm_state41;
            break;
        case 1099511627776 : 
            ap_NS_fsm = ap_ST_fsm_state42;
            break;
        case 2199023255552 : 
            ap_NS_fsm = ap_ST_fsm_state43;
            break;
        case 4398046511104 : 
            ap_NS_fsm = ap_ST_fsm_state44;
            break;
        case 8796093022208 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<44>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

