// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __fdot_3d_l_conv_pobkb_H__
#define __fdot_3d_l_conv_pobkb_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct fdot_3d_l_conv_pobkb_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 8;
  static const unsigned AddressRange = 20;
  static const unsigned AddressWidth = 5;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(fdot_3d_l_conv_pobkb_ram) {
        ram[0] = "0b00011011";
        ram[1] = "0b11111111";
        ram[2] = "0b00001111";
        ram[3] = "0b11111111";
        ram[4] = "0b00001001";
        ram[5] = "0b11111111";
        ram[6] = "0b11100000";
        ram[7] = "0b01111111";
        ram[8] = "0b01011110";
        ram[9] = "0b01111111";
        ram[10] = "0b11110001";
        ram[11] = "0b11111111";
        ram[12] = "0b11100100";
        ram[13] = "0b01111111";
        ram[14] = "0b11101010";
        ram[15] = "0b01111111";
        ram[16] = "0b11110111";
        ram[17] = "0b11111111";
        ram[18] = "0b00100101";
        ram[19] = "0b11111111";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(fdot_3d_l_conv_pobkb) {


static const unsigned DataWidth = 8;
static const unsigned AddressRange = 20;
static const unsigned AddressWidth = 5;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


fdot_3d_l_conv_pobkb_ram* meminst;


SC_CTOR(fdot_3d_l_conv_pobkb) {
meminst = new fdot_3d_l_conv_pobkb_ram("fdot_3d_l_conv_pobkb_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~fdot_3d_l_conv_pobkb() {
    delete meminst;
}


};//endmodule
#endif
