#pragma line 1 "pynqebnnrealcodes/ebnn_mnist.c" ::: 0
#pragma line 1 "pynqebnnrealcodes/ebnn_mnist.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 147 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "D:/Vivado/Vivado/2017.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 12
#pragma line 296 "D:/Vivado/Vivado/2017.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 13
#pragma line 8 "<command line>" 2 ::: 129
#pragma line 1 "<built-in>" 2 ::: 130
#pragma line 1 "pynqebnnrealcodes/ebnn_mnist.c" 2 ::: 131
#pragma line 1 "pynqebnnrealcodes/ebnn.h" 1 ::: 132
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 136
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 145
#pragma line 10 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 146
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 1 3 ::: 147
#pragma line 10 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 148
#pragma line 277 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 149
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 1 3 ::: 150
#pragma line 13 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 151
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 152
#pragma line 674 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 153
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_directx.h" 1 3 ::: 154
#pragma line 674 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 155
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_ddk.h" 1 3 ::: 157
#pragma line 675 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 158
#pragma line 13 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 2 3 ::: 159
#pragma line 102 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 179
#pragma line 277 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 181
#pragma line 370 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 185
#pragma line 380 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 187
#pragma line 392 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 189
#pragma line 405 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 191
#pragma line 418 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 193
#pragma line 428 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 195
#pragma line 456 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 206
#pragma line 607 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 226
#pragma line 9 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 288
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_push.h" 1 3 ::: 291
#pragma line 11 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 292
#pragma line 26 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 296
#pragma line 84 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 308
#pragma line 120 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 327
#pragma line 157 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 329
#pragma line 312 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 475
#pragma line 330 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 483
#pragma line 373 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 519
#pragma line 417 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 554
#pragma line 475 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 584
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 1 3 ::: 620
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 629
#pragma line 9 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 2 3 ::: 630
#pragma line 509 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 631
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_pop.h" 1 3 ::: 634
#pragma line 511 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 635
#pragma line 5 "pynqebnnrealcodes/ebnn.h" 2 ::: 636
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/include\\stdint.h" 1 3 4 ::: 637
#pragma line 33 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/include\\stdint.h" 3 4 ::: 638
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdint.h" 1 3 4 ::: 639
#pragma line 28 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdint.h" 3 4 ::: 640
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 4 ::: 641
#pragma line 28 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdint.h" 2 3 4 ::: 642
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/include\\stddef.h" 1 3 4 ::: 647
#pragma line 31 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/include\\stddef.h" 3 4 ::: 648
#pragma line 32 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdint.h" 2 3 4 ::: 659
#pragma line 33 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/include\\stdint.h" 2 3 4 ::: 698
#pragma line 6 "pynqebnnrealcodes/ebnn.h" 2 ::: 699
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/include\\float.h" 1 3 4 ::: 700
#pragma line 33 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/include\\float.h" 3 4 ::: 701
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\float.h" 1 3 4 ::: 702
#pragma line 28 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\float.h" 3 4 ::: 703
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 4 ::: 704
#pragma line 28 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\float.h" 2 3 4 ::: 705
#pragma line 136 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\float.h" 3 4 ::: 706
#pragma line 155 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\float.h" 3 4 ::: 713
#pragma line 169 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\float.h" 3 4 ::: 719
#pragma line 33 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/include\\float.h" 2 3 4 ::: 732
#pragma line 7 "pynqebnnrealcodes/ebnn.h" 2 ::: 733
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/include\\limits.h" 1 3 4 ::: 734
#pragma line 38 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/include\\limits.h" 3 4 ::: 735
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\limits.h" 1 3 4 ::: 736
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 4 ::: 742
#pragma line 6 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\limits.h" 2 3 4 ::: 743
#pragma line 38 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/include\\limits.h" 2 3 4 ::: 744
#pragma line 8 "pynqebnnrealcodes/ebnn.h" 2 ::: 745
#pragma line 2 "pynqebnnrealcodes/ebnn_mnist.c" 2 ::: 1334
