#pragma line 1 "pynqebnnrealcodes/ebnn_mnist.c" ::: -10
#pragma line 1 "pynqebnnrealcodes/ebnn_mnist.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 147 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "D:/Vivado/Vivado/2017.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 2
#pragma line 296 "D:/Vivado/Vivado/2017.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 3
#pragma line 8 "<command line>" 2 ::: 119
#pragma line 1 "<built-in>" 2 ::: 120
#pragma line 1 "pynqebnnrealcodes/ebnn_mnist.c" 2 ::: 121
#pragma line 1 "pynqebnnrealcodes/ebnn.h" 1 ::: 122
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 126
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 135
#pragma line 10 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 136
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 1 3 ::: 137
#pragma line 10 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 138
#pragma line 277 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 139
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 1 3 ::: 140
#pragma line 13 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 141
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 142
#pragma line 674 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 143
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_directx.h" 1 3 ::: 144
#pragma line 674 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 145
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_ddk.h" 1 3 ::: 147
#pragma line 675 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 148
#pragma line 13 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 2 3 ::: 149
#pragma line 102 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 169
#pragma line 277 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 171
#pragma line 370 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 175
#pragma line 380 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 177
#pragma line 392 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 179
#pragma line 405 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 181
#pragma line 418 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 183
#pragma line 428 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 185
#pragma line 456 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 196
#pragma line 607 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 216
#pragma line 9 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 278
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_push.h" 1 3 ::: 281
#pragma line 11 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 282
#pragma line 26 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 286
#pragma line 84 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 298
#pragma line 120 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 317
#pragma line 157 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 319
#pragma line 312 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 465
#pragma line 330 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 473
#pragma line 373 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 509
#pragma line 417 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 544
#pragma line 475 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 574
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 1 3 ::: 610
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 619
#pragma line 9 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 2 3 ::: 620
#pragma line 509 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 621
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_pop.h" 1 3 ::: 624
#pragma line 511 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 625
#pragma line 5 "pynqebnnrealcodes/ebnn.h" 2 ::: 626
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/include\\stdint.h" 1 3 4 ::: 627
#pragma line 33 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/include\\stdint.h" 3 4 ::: 628
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdint.h" 1 3 4 ::: 629
#pragma line 28 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdint.h" 3 4 ::: 630
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 4 ::: 631
#pragma line 28 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdint.h" 2 3 4 ::: 632
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/include\\stddef.h" 1 3 4 ::: 637
#pragma line 31 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/include\\stddef.h" 3 4 ::: 638
#pragma line 32 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdint.h" 2 3 4 ::: 649
#pragma line 33 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/include\\stdint.h" 2 3 4 ::: 688
#pragma line 6 "pynqebnnrealcodes/ebnn.h" 2 ::: 689
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/include\\float.h" 1 3 4 ::: 690
#pragma line 33 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/include\\float.h" 3 4 ::: 691
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\float.h" 1 3 4 ::: 692
#pragma line 28 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\float.h" 3 4 ::: 693
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 4 ::: 694
#pragma line 28 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\float.h" 2 3 4 ::: 695
#pragma line 136 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\float.h" 3 4 ::: 696
#pragma line 155 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\float.h" 3 4 ::: 703
#pragma line 169 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\float.h" 3 4 ::: 709
#pragma line 33 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/include\\float.h" 2 3 4 ::: 722
#pragma line 7 "pynqebnnrealcodes/ebnn.h" 2 ::: 723
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/include\\limits.h" 1 3 4 ::: 724
#pragma line 38 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/include\\limits.h" 3 4 ::: 725
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\limits.h" 1 3 4 ::: 726
#pragma line 1 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 4 ::: 732
#pragma line 6 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\limits.h" 2 3 4 ::: 733
#pragma line 38 "D:/Vivado/Vivado/2017.4/win64/tools/clang/bin/../lib/clang/3.1/include\\limits.h" 2 3 4 ::: 734
#pragma line 8 "pynqebnnrealcodes/ebnn.h" 2 ::: 735
#pragma line 2 "pynqebnnrealcodes/ebnn_mnist.c" 2 ::: 1324
